import type { CatalogKink, Kink } from "@/types";

export { CATEGORIES, kinkCategoryLabel, KINK_CATEGORY_DEFINITIONS } from "@/lib/kinkCategories";

// level 1 = beginner (kort)  |  2 = gevorderd (normaal)  |  3 = ervaren (lang)  |  4 = diepgaand (alles)
export const KINKS: CatalogKink[] = [
  // ─── Impact Play ───────────────────────────────────────────────────────────
  {
    id: "spanking_hand",
    name: "Spanking (hand)",
    category: "impact",
    level: 1,
    description: "Slaan met de hand op het zitvlak. Een van de meest toegankelijke impactspellen met directe feedback. Communiceer van tevoren de gewenste intensiteit.",
  },
  {
    id: "spanking_implement",
    name: "Spanking (implement)",
    category: "impact",
    level: 2,
    description: "Slaan met een voorwerp zoals een spatel of paddle. Intensere sensaties dan met de hand, met meer controle over kracht en plek. Goede warming-up en aftercare zijn essentieel.",
  },
  {
    id: "flogging",
    name: "Flogging",
    category: "impact",
    level: 2,
    description: "Zweepspel met meerdere leren of touwriemen (flogger). Kan variëren van zacht en sensueel tot intens. Vereist kennis van veilige zones op het lichaam.",
  },
  {
    id: "caning",
    name: "Caning",
    category: "impact",
    level: 3,
    description: "Stokslagen met een dunne rietachtige stok. Scherpe, intense pijn die lang nawerkt. Vereist ervaring en kennis van veilige slagplaatsen.",
  },
  {
    id: "cropping",
    name: "Crop",
    category: "impact",
    level: 2,
    description: "Gebruik van een rijzweep (crop) voor gerichte tikken. Preciezer dan flogging, goed te doseren. Populair in paardenspel en dominante dynamieken.",
  },
  {
    id: "paddling",
    name: "Paddling",
    category: "impact",
    level: 2,
    description: "Slaan met een paddle (plat, stijf slagwerktuig). Geeft een diepe, dofige klap. Graduele opbouw van intensiteit is aan te raden.",
  },
  {
    id: "whipping",
    name: "Whipping",
    category: "impact",
    level: 3,
    description: "Zweepspel met een lange, dunne zweep. Vereist techniek en afstandsinschatting. Alleen voor ervaren spelers vanwege risico op onbedoelde treffers.",
  },
  {
    id: "belt",
    name: "Belt",
    category: "impact",
    level: 2,
    description: "Gebruik van een riem als slagwerktuig. Toegankelijk en vertrouwd aanvoelend. Communiceer duidelijk over intensiteit en gewenste plaatsen.",
  },
  {
    id: "slapping_face",
    name: "Face slapping",
    category: "impact",
    level: 3,
    description: "Gezichtsklappen als daad van dominantie of vernedering. Vereist uitdrukkelijke toestemming en kennis van veilige technieken. Nooit hard of onverwacht.",
  },
  {
    id: "punching",
    name: "Punching / thuding",
    category: "impact",
    level: 3,
    description: "Vuistslagen of druktechnieken op vlezig lichaamsweefsel (thudding). Diepe, botsbewegingen eerder dan scherpe pijn. Uitsluitend voor gevorderde spelers met anatomische kennis.",
  },
  {
    id: "trampling",
    name: "Trampling",
    category: "impact",
    level: 3,
    description: "Lopen, staan of trappen op het lichaam van de partner. Vereist gewichtsverdeling en kennis van kwetsbare lichaamsdelen. Altijd met volledige toestemming en voorzichtigheid.",
  },

  // ─── Bondage ───────────────────────────────────────────────────────────────
  {
    id: "rope_bondage",
    name: "Rope bondage",
    aliases: ["Touwbondage", "Vastbinden met touw"],
    category: "bondage",
    level: 2,
    description: "Vastbinden met touw, waarbij de submissieve partner beperkt wordt in bewegingsvrijheid. Geeft een gevoel van controle en overgave. Leer altijd knippen voor noodgevallen.",
  },
  {
    id: "shibari",
    name: "Shibari (rope art)",
    category: "bondage",
    level: 3,
    description: "Japanse bindkunst waarbij touw esthetisch en sensueel om het lichaam wordt geweven. Vereist uitgebreide training; ophangen (suspensie) is een aparte, gevorderdere stap.",
  },
  {
    id: "handcuffs",
    name: "Handcuffs / metal cuffs",
    category: "bondage",
    level: 1,
    description: "Metalen handboeien voor polsbeperking. Snel aan te leggen, maar kunnen bij verkeerde druk pijnlijk zijn. Houd altijd een sleutel bij de hand.",
  },
  {
    id: "leather_cuffs",
    name: "Leather cuffs",
    category: "bondage",
    level: 1,
    description: "Leren manchetten voor pols of enkel. Comfortabeler dan metaal, geschikt voor langduriger gebruik. Een veelzijdige basis voor bondage.",
  },
  {
    id: "spreader_bar",
    name: "Spreader bar",
    category: "bondage",
    level: 2,
    description: "Starre stang die armen of benen op afstand houdt. Geeft een gevoel van kwetsbaarheid en expositie. Comfortabele plek en tijdslimiet zijn belangrijk.",
  },
  {
    id: "hogtie",
    name: "Hogtie",
    category: "bondage",
    level: 3,
    description: "Verbinden van polsen en enkels aan de achterkant van het lichaam. Intensieve positie die de bewegingsvrijheid volledig beperkt. Regelmatige check-ins zijn noodzakelijk.",
  },
  {
    id: "mummification",
    name: "Mummification",
    category: "bondage",
    level: 4,
    description: "Het volledig inbakeren van het lichaam met tape, latex of stof. Geeft een intens gevoel van beperktheid en sensorische overweldiging. Nooit alleen uitvoeren.",
  },
  {
    id: "straitjacket",
    name: "Straitjacket",
    category: "bondage",
    level: 4,
    description: "Dwangbuis die armen en torso fixeert. Symbool van volledige controle. Altijd een veilig signaal afspreken.",
  },
  {
    id: "chastity",
    name: "Chastity device",
    category: "bondage",
    level: 3,
    description: "Kuisheidsapparaat dat seksuele activiteit beperkt. Onderdeel van orgasme- of seksuele controle. Hygiëne en regelmatige controle zijn essentieel.",
  },
  {
    id: "gag_ball",
    name: "Ball gag",
    category: "bondage",
    level: 2,
    description: "Balknevel die spreken verhindert. Geeft een gevoel van stilte en overgave. Gebruik non-verbale safewords (kloppen, knijpen) als alternatief.",
  },
  {
    id: "gag_bit",
    name: "Bit gag",
    category: "bondage",
    level: 2,
    description: "Bit-achtige knevel, vergelijkbaar met een paardenbijt. Laat meer speekselafvloed toe dan een balknevel. Gebruik non-verbale safewords.",
  },
  {
    id: "gag_tape",
    name: "Tape gag",
    category: "bondage",
    level: 2,
    description: "Tape over de mond als knevel. Eenvoudig en visueel impactvol. Zorg dat de neusgangen vrij zijn en gebruik huidvriendelijke tape.",
  },
  {
    id: "blindfold",
    name: "Blindfold",
    category: "bondage",
    level: 1,
    description: "Oogbedekking die zicht ontneemt. Vergroot andere zintuigen en het gevoel van kwetsbaarheid. Een toegankelijke introductie tot sensorische spelen.",
  },
  {
    id: "hood",
    name: "Hood / sensory deprivation hood",
    category: "bondage",
    level: 3,
    description: "Kap over het hoofd die zicht en soms gehoor ontneemt. Intensief sensorisch hulpmiddel. Zorg altijd voor voldoende luchttoevoer.",
  },
  {
    id: "collar_leash",
    name: "Collar & leash",
    category: "bondage",
    level: 1,
    description: "Halsband en riem als symbool van eigenaarschap en dynamiek. Kan puur symbolisch zijn of in actief spel gebruikt worden. Draag een veilige, juist passende halsband.",
  },

  // ─── Power Exchange ─────────────────────────────────────────────────────────
  {
    id: "dominance_submission",
    name: "D/s dynamic",
    category: "power",
    level: 1,
    description: "Een consensuele dynamiek waarbij één persoon leidt (dominant) en de ander volgt (submissief). De basis van veel BDSM-relaties. Goede communicatie is de kern.",
  },
  {
    id: "master_slave",
    name: "Master / slave dynamic",
    category: "power",
    level: 3,
    description: "Een intensievere D/s-dynamiek waarbij de submissieve partner uitgebreide controle overdraagt. Vereist diepe wederzijdse kennis en vertrouwen. Altijd grenzen en herziening afspreken.",
  },
  {
    id: "owner_pet",
    name: "Owner / pet dynamic",
    category: "power",
    level: 2,
    description: "Een dynamiek waarbij één persoon de 'eigenaar' is en de ander zich als huisdier gedraagt. Kan speels en sensueel zijn. Inclusief non-verbale communicatie en beloningen.",
  },
  {
    id: "collaring",
    name: "Collaring ceremony",
    category: "rituals",
    level: 3,
    description: "Een ceremoniële handeling waarbij een halsband overgedragen wordt als symbool van toewijding en eigenaarschap. Vergelijkbaar met een verloving binnen sommige BDSM-relaties.",
  },
  {
    id: "rules_protocols",
    name: "Rules & protocols",
    category: "rituals",
    level: 2,
    description: "Het opstellen van regels, gewoonten en protocollen die de dynamiek structureren. Geeft duidelijkheid en richting. Bespreek regelmatig of regels nog passend zijn.",
  },
  {
    id: "punishment",
    name: "Straf als correctie (kader)",
    category: "discipline",
    level: 2,
    description: "Het fundament van deze categorie: straf bestaat om afgesproken regels te herstellen, nooit om te straffen om het straffen. Regel, overtreding en gevolg zijn vooraf bekend; de straf is proportioneel, wordt nooit uit woede gegeven en eindigt in herstel — schone lei, geen wrok.",
  },
  {
    id: "humiliation_verbal",
    name: "Verbal humiliation",
    category: "power",
    level: 2,
    description: "Verbale vernedering, schelden of kleinerende uitspraken als onderdeel van spel. Vereist expliciete toestemming en kennis van triggers. Wat vernederend is, is persoonlijk.",
  },
  {
    id: "degradation",
    name: "Degradation",
    category: "power",
    level: 3,
    description: "Diepgaande vernedering via taal, acties of situaties. Intensief en emotioneel geladen. Uitgebreide nabespreking is altijd nodig.",
  },
  {
    id: "praise_kink",
    name: "Praise kink",
    category: "power",
    level: 1,
    description: "Opwinding door goedkeuring, lof en bevestiging. Het tegenovergestelde van vernedering, maar net zo krachtig. Toegankelijk en positief van aard.",
  },
  {
    id: "objectification",
    name: "Objectification",
    category: "power",
    level: 3,
    description: "De ander behandelen als een object zonder eigen wil. Intensief en vraagt om volledig vertrouwen. Regelmatige check-ins zijn van belang.",
  },
  {
    id: "forced_orgasm",
    name: "Forced orgasm",
    category: "power",
    level: 2,
    description: "Het afdwingen van een orgasme, ook als de partner dit probeert te weigeren. Vereist duidelijke toestemming en kennis van elkaars lichaam.",
  },
  {
    id: "orgasm_denial",
    name: "Orgasm denial / edging",
    category: "power",
    level: 2,
    description: "Het herhaaldelijk opbouwen van opwinding zonder ontlading toe te staan. Vergroot seksuele spanning en controle. Communiceer over grenzen en duur.",
  },
  {
    id: "orgasm_control",
    name: "Orgasm control / permission",
    category: "power",
    level: 2,
    description: "De dominant beslist wanneer, hoe of of de partner een orgasme mag hebben. Onderdeel van uitgebreidere machtsuitwisseling. Vereist wederzijdse communicatie.",
  },
  {
    id: "service",
    name: "Service (domestic / personal)",
    category: "power",
    level: 1,
    description: "De submissieve partner verleent diensten (huishoudelijk, persoonlijk) als uiting van toewijding. Kan buiten seksuele contexten plaatsvinden. Grenzen gelden ook hier.",
  },
  {
    id: "financial_domination",
    name: "Financial domination",
    category: "power",
    level: 4,
    description: "De submissieve partner draagt financiële controle over aan de dominant. Uiterst gevoelig gebied. Altijd met duidelijke grenzen en buiten staat van kwetsbaarheid bespreken.",
  },

  // ─── Role Play ──────────────────────────────────────────────────────────────
  {
    id: "cnc",
    name: "Consensual non-consent (CNC)",
    category: "roleplay",
    level: 3,
    description: "Consensuele non-consent — spelen met de fantasie van gedwongen seks, terwijl alles vooraf afgesproken is. Vereist intensieve voorbereiding en duidelijke safewords.",
  },
  {
    id: "interrogation",
    name: "Interrogation scene",
    category: "roleplay",
    level: 3,
    description: "Verhoor-scène waarbij één persoon informatie probeert te ontlokken via druk. Theatraal en spanningsvol. Sfeer en grenzen altijd van tevoren afbakenen.",
  },
  {
    id: "capture_scene",
    name: "Capture / kidnapping scene",
    category: "roleplay",
    level: 3,
    description: "Ontvoerings- of vangstscène. Adrenalineverhogende fantasie. Vereist uitgebreide planning en duidelijke stopwoorden.",
  },
  {
    id: "teacher_student",
    name: "Teacher / student",
    category: "roleplay",
    level: 2,
    description: "Gezaghebbende leerkracht tegenover gehoorzame leerling. Klassiek machtspel. Grenzen rond vernedering en straf van tevoren bespreken.",
  },
  {
    id: "boss_employee",
    name: "Boss / employee",
    category: "roleplay",
    level: 2,
    description: "Baas-medewerker dynamiek met nadruk op hiërarchie en gehoorzaamheid. Kan licht of intens worden. Grenzen en scenario duidelijk afspreken.",
  },
  {
    id: "doctor_patient",
    name: "Doctor / patient",
    category: "roleplay",
    level: 2,
    description: "Medische rollenspellen met een gezaghebbende 'arts' en kwetsbare 'patiënt'. Verkenning van vertrouwen en lichamelijkheid. Grenzen over aanraking zijn essentieel.",
  },
  {
    id: "strangers_scene",
    name: "Strangers scene",
    category: "roleplay",
    level: 2,
    description: "Spelen alsof de partners vreemden zijn die elkaar ontmoeten. Geeft een gevoel van spanning en nieuwheid. Scenario en grenzen altijd van tevoren doornemen.",
  },
  {
    id: "brat_tamer",
    name: "Brat / tamer dynamic",
    category: "power",
    level: 2,
    description: "De submissieve partner (brat) daagt de dominant (tamer) bewust uit. Speels en provocerend. Duidelijke grenzen over straf en vergelding zijn noodzakelijk.",
  },

  // ─── Sensation Play ─────────────────────────────────────────────────────────
  {
    id: "wax_play",
    name: "Wax play",
    category: "sensation",
    level: 2,
    description: "Druppelen van hete kaarsenwas op de huid voor warmtesensaties. Begin altijd laag (veilige hoogte) en gebruik kaarsen zonder additieven. Nooit in de buurt van haar.",
  },
  {
    id: "ice_play",
    name: "Ice play",
    category: "sensation",
    level: 1,
    description: "IJsblokjes over de huid bewegen voor koude, tintelende sensaties. Complementair aan warmtespelen. Altijd bewegen, nooit statisch op gevoelige plekken houden.",
  },
  {
    id: "knife_play",
    name: "Knife play",
    category: "sensation",
    level: 3,
    description: "Gebruik van een mes voor spanning, koude sensaties en psychologische intensiteit. Nooit bedoeld om te snijden. Vereist ervaring en kalmte van beide partners.",
  },
  {
    id: "needle_play",
    name: "Needle play",
    category: "sensation",
    level: 3,
    description: "Naalden door de huid steken voor intense sensaties en esthetische effecten. Vereist medische kennis, steriele materialen en ervaring. Altijd in veilige context.",
  },
  {
    id: "fire_play",
    name: "Fire play",
    category: "sensation",
    level: 4,
    description: "Gebruik van vuur (vlam, alcohol) op of nabij de huid. Visueel indrukwekkend en thermisch intens. Vereist training, brandbestrijder bij de hand en ervaren speler.",
  },
  {
    id: "wartenberg_wheel",
    name: "Wartenberg wheel",
    category: "sensation",
    level: 2,
    description: "Pinwiel dat over de huid gerold wordt voor tintelende sensaties. Kan licht krabben tot scherp prikken. Schoon instrument, nooit bij open wonden.",
  },
  {
    id: "pinching",
    name: "Pinching",
    category: "sensation",
    level: 2,
    description: "Knijpen van huid voor scherpe, gelokaliseerde pijn — vingers, nagels of een tang. Eenvoudig maar intens. Communiceer over voorkeurzones en intensiteit.",
  },
  {
    id: "scratching",
    name: "Scratching",
    category: "sensation",
    level: 1,
    description: "Krabben met nagels of krabwerktuig voor tintelende, brandende sensaties. Kan sporen achterlaten. Communiceer over de zichtbaarheid van tekens.",
  },
  {
    id: "biting",
    name: "Biting",
    category: "sensation",
    level: 1,
    description: "Bijten als uitdrukking van verlangen of dominantie. Intensiteit varieert van zacht tot merkend. Vermijd locaties met grote bloedvaten.",
  },
  {
    id: "tickling",
    name: "Tickling",
    category: "sensation",
    level: 1,
    description: "Kietelen als onderdeel van spel, soms in combinatie met bondage. Kan intens en overweldigend zijn. Safeword is essentieel bij verzwakte positie.",
  },
  {
    id: "choking",
    name: "Choking / breath restriction",
    category: "sensation",
    level: 3,
    description: "Druk op de keel of nek voor een gevoel van controle en hypoxie-gerelateerde opwinding. Extreem risico op ernstig letsel of overlijden. Alleen voor gevorderden met diepgaande kennis van anatomie.",
  },
  {
    id: "facesitting",
    name: "Facesitting / smothering",
    category: "power",
    level: 2,
    description: "Zitten op het gezicht van de partner, waarbij ademhaling gecontroleerd wordt. Vereist communicatie over ademruimte. Altijd een non-verbaal stopsignaal afspreken.",
  },
  {
    id: "hair_pulling",
    name: "Hair pulling",
    category: "sensation",
    level: 1,
    description: "Trekken aan het haar als daad van dominantie of verlangen. Grijp bij de wortel voor meer controle. Vermijd schokken of rukken.",
  },
  {
    id: "marking",
    name: "Marking / bruising",
    category: "sensation",
    level: 2,
    description: "Kneuzing of bijtreken op het lichaam achterlaten als teken van eigenaarschap. Bespreek of en waar tekens zichtbaar mogen zijn buiten de speelruimte.",
  },
  {
    id: "scarification",
    name: "Scarification / branding",
    category: "sensation",
    level: 4,
    description: "Permanente littekens aanbrengen als lichaamsmodi. Onomkeerbaar en vereist medische kennis. Uitsluitend voor gevorderden met professionele begeleiding.",
  },

  // ─── Exhibition & Voyeurism ─────────────────────────────────────────────────
  {
    id: "exhibitionism",
    name: "Exhibitionism",
    category: "exhibition",
    level: 1,
    description: "Opwinding door het tonen van het eigen lichaam aan anderen. Kan variëren van lingerie tot publieke naaktheid. Zorg altijd dat toeschouwers toestemming hebben gegeven.",
  },
  {
    id: "voyeurism",
    name: "Voyeurism",
    category: "exhibition",
    level: 1,
    description: "Opwinding door het (consensueel) observeren van anderen. Nooit zonder volledige toestemming van de geobserveerde persoon.",
  },
  {
    id: "public_play",
    name: "Public play (discreet)",
    category: "exhibition",
    level: 3,
    description: "Discreet spelen in publieke ruimtes (bijv. knijpen, safeword-fluisteren). Uitdagend en riskant. Altijd discreet en zonder onbewillige derden te betrekken.",
  },
  {
    id: "dogging",
    name: "Outdoor / dogging",
    category: "exhibition",
    level: 3,
    description: "Seks of vertoning in openbare (buitenlucht)plekken, soms voor andere aanwezigen. Juridisch gevoelig en vereist bewustzijn van wetten per land.",
  },
  {
    id: "watching_others",
    name: "Watching others (in person)",
    category: "exhibition",
    level: 2,
    description: "Consensueel anderen observeren tijdens seksuele activiteit. Vereist duidelijke afspraken met alle betrokkenen. Privacy van de geobserveerden staat voorop.",
  },
  {
    id: "being_watched",
    name: "Being watched",
    category: "exhibition",
    level: 1,
    description: "Opwinding door zelf geobserveerd te worden tijdens seksuele activiteit. Bespreek wie mag kijken en in welke context.",
  },
  {
    id: "recording",
    name: "Recording / photography (private)",
    category: "exhibition",
    level: 3,
    description: "Privéopnames of -foto's maken tijdens seksuele activiteit. Uitsluitend met volledige toestemming. Bespreek opslaglocatie, deling en verwijdering.",
  },
  {
    id: "webcam",
    name: "Webcam / streaming (private)",
    category: "exhibition",
    level: 3,
    description: "Privéstreaming of webcamseks voor een geselecteerd publiek. Bespreek wie toegang heeft. Nooit opslaan of delen zonder expliciete toestemming.",
  },

  // ─── Fetishes ───────────────────────────────────────────────────────────────
  {
    id: "feet",
    name: "Foot worship / feet",
    category: "body_focus",
    level: 1,
    description: "Opwinding door voeten: aanraken, kussen, masseren of aanbidden. Een van de meest voorkomende fetisjen. Grenzen rond hygiëne en aanraking van tevoren bespreken.",
  },
  {
    id: "leather",
    name: "Leather",
    category: "materials_scent",
    level: 2,
    description: "Opwinding door leer als materiaal: geur, aanraking, kleding. Leer draagt een sterke symbolische lading in de BDSM-cultuur.",
  },
  {
    id: "latex_rubber",
    name: "Latex / rubber",
    category: "materials_scent",
    level: 2,
    description: "Opwinding door latex of rubber kleding, die het lichaam strak omsluit. Aandacht voor latexallergie en smeermiddel voor het aantrekken.",
  },
  {
    id: "lingerie",
    name: "Lingerie / stockings",
    category: "materials_scent",
    level: 1,
    description: "Opwinding door het dragen of zien van ondergoed of kousen. Breed en toegankelijk fetisj. Communiceer over wat gewenste kledingstukken zijn.",
  },
  {
    id: "uniforms",
    name: "Uniforms / costumes",
    category: "roleplay",
    level: 2,
    description: "Opwinding door uniformen of kostuums (politie, verpleging, etc.). Verbindt rollenspel met fetisj. Bespreek welke rollen en scenario's gewenst zijn.",
  },
  {
    id: "furry",
    name: "Fursuit / furry play",
    category: "pet_play",
    level: 3,
    description: "Opwinding door het dragen van een dierenkostuum (fursuit) of furry-identiteit. Niche maar vergelijkbaar met andere rollenspelen. Communiceer over grenzen.",
  },
  {
    id: "cuckolding",
    name: "Cuckolding / hotwifing",
    category: "exhibition",
    level: 3,
    description: "Opwinding waarbij één partner toekijkt of ervan weet dat de ander seks heeft met een derde. Vereist diepgaand vertrouwen en duidelijke grenzen rond seksualiteit en veiligheid.",
  },
  {
    id: "voyeur_sharing",
    name: "Sharing / group play",
    category: "exhibition",
    level: 3,
    description: "Delen van een partner met anderen of groepsseks. Uitgebreide communicatie, seksuele gezondheidsafspraken en grenzen zijn essentieel.",
  },
  {
    id: "body_worship",
    name: "Body worship",
    category: "body_focus",
    level: 1,
    description: "Aanbidding van het lichaam van de partner via aanraking, kussen en verbale devotie. Sensueel en verbindend. Bespreek welke lichaamsdelen welkom zijn.",
  },
  {
    id: "stocking_worship",
    name: "Stocking / lingerie worship",
    category: "body_focus",
    level: 2,
    description: "Opwinding door kousen of lingerie van de partner, inclusief aanraking of besnuffeling. Vergelijkbaar met voetfetisj maar gericht op kleding.",
  },

  // ─── Fluid & Bodily ─────────────────────────────────────────────────────────
  {
    id: "spitting",
    name: "Spitting",
    category: "fluids",
    level: 2,
    description: "Spugen op de partner als daad van vernedering of dominantie. Vereist expliciete toestemming. Hygiënisch en emotioneel gevoelig.",
  },
  {
    id: "scat",
    name: "Scat play",
    category: "fluids",
    level: 4,
    description: "Spelen met ontlasting. Uiterst niche en vereist diepgaande afspraken, hygiëneprotocollen en gezondheidsbewustzijn.",
  },
  {
    id: "cum_play",
    name: "Cum play / facials",
    category: "fluids",
    level: 1,
    description: "Spelen met sperma, waaronder facials of op het lichaam. Communiceer over seksuele gezondheid, testen en wensen.",
  },
  {
    id: "squirting",
    name: "Squirting",
    category: "fluids",
    level: 2,
    description: "Vloeibare ontlading bij genitale stimulatie. Kan voor sommigen intens zijn. Bespreek of dit gewenst is en bereid de omgeving voor.",
  },
  {
    id: "swallowing",
    name: "Swallowing",
    category: "fluids",
    level: 1,
    description: "Sperma inslikken. Communiceer over seksuele gezondheid en tests. Persoonlijke voorkeur dient altijd gerespecteerd te worden.",
  },
  {
    id: "menstrual_play",
    name: "Menstrual play",
    category: "fluids",
    level: 2,
    description: "Seks of spel tijdens de menstruatie. Normaal en veilig voor de meesten, maar bespreek comfort en hygiëne van tevoren.",
  },

  // ─── Anal & Penetration ─────────────────────────────────────────────────────
  {
    id: "anal_sex",
    name: "Anal sex",
    category: "penetration",
    level: 2,
    description: "Anale penetratie met penis of speelgoed. Vereist veel glijmiddel, opwarming en communicatie. Nooit haastig beginnen.",
  },
  {
    id: "anal_fingering",
    name: "Anal fingering",
    category: "penetration",
    level: 1,
    description: "Anale penetratie met vingers als verkenning of voorbereiding. Altijd korte nagels en glijmiddel gebruiken.",
  },
  {
    id: "pegging",
    name: "Pegging / strap-on",
    category: "penetration",
    level: 2,
    description: "Penetratie van de man (of partner zonder penis) met een strap-on door de partner. Communiceer over maat, snelheid en positie.",
  },
  {
    id: "butt_plug",
    name: "Butt plug (wear)",
    category: "penetration",
    level: 1,
    description: "Een anaal hulpmiddel om gedragen te worden, van kort tot langdurig. Altijd een bredere basis dan de plug zelf, zodat het niet verloren kan gaan.",
  },
  {
    id: "anal_beads",
    name: "Anal beads",
    category: "penetration",
    level: 2,
    description: "Een reeks kralen die anaal ingebracht en uitgetrokken worden voor sensatie. Begin klein, gebruik glijmiddel en communiceer over tempo.",
  },
  {
    id: "fisting_anal",
    name: "Anal fisting",
    category: "penetration",
    level: 3,
    description: "Anale penetratie met de volledige hand. Vereist uitgebreide voorbereiding, glijmiddel en vertrouwen. Alleen voor gevorderden.",
  },
  {
    id: "fisting_vaginal",
    name: "Vaginal fisting",
    category: "penetration",
    level: 3,
    description: "Vaginale penetratie met de volledige hand. Uitgebreide opwarming, glijmiddel en communicatie zijn noodzakelijk.",
  },
  {
    id: "deep_throat",
    name: "Deep throat",
    category: "sensation",
    level: 2,
    description: "Diep oraal seksueel contact waarbij de partner de keel penetreert. Communiceer over ademhaling en non-verbale stopsignalen.",
  },
  {
    id: "rough_sex",
    name: "Rough sex",
    category: "power",
    level: 2,
    description: "Intens, ruw seksueel contact dat agressiviteit, kracht en dominantie omvat. Bespreek intensiteit, grenzen en aftercare van tevoren uitvoerig.",
  },

  // ─── Aftercare ──────────────────────────────────────────────────────────────
  {
    id: "aftercare_physical",
    name: "Physical aftercare (cuddling, blankets)",
    category: "aftercare",
    level: 1,
    description: "Fysieke nazorg na spelen: knuffelen, een deken, masseren. Helpt het lichaam en de geest terug te keren naar een veilige basistoestand.",
  },
  {
    id: "aftercare_verbal",
    name: "Verbal reassurance / check-ins",
    category: "aftercare",
    level: 1,
    description: "Verbale geruststelling na een scène: bevestiging, complimenten, check-ins. Helpt emotionele verwerking na intensief spel.",
  },
  {
    id: "aftercare_alone",
    name: "Alone time after scenes",
    category: "aftercare",
    level: 2,
    description: "Behoefte aan alleen-tijd na een scène om te verwerken. Soms meer herstellend dan gezelschap. Respecteer deze voorkeur.",
  },
  {
    id: "aftercare_food",
    name: "Food / drink after scenes",
    category: "aftercare",
    level: 1,
    description: "Eten of drinken na een scène voor herstel van energie en bloedsuiker. Zoet en licht is vaak het beste. Zorg dat dit klaarstaat.",
  },
  {
    id: "aftercare_journaling",
    name: "Journaling / reflection after scenes",
    category: "aftercare",
    level: 2,
    description: "Schrijven of reflecteren na een scène als verwerkingstool. Kan helpen bij het begrijpen van emoties en het verbeteren van toekomstige scènes.",
  },

  // ─── Uiterlijk & Kleding ───────────────────────────────────────────────────
  {
    id: "hoge_hakken_dragen",
    name: "Hoge hakken dragen",
    category: "appearance",
    level: 1,
    description: "Het dragen van hoge hakken als fetish-element of op commando. Kan zowel erotisch als onderdeel van een D/s-protocol zijn.",
  },
  {
    id: "korset_dragen",
    name: "Korset dragen",
    category: "appearance",
    level: 1,
    description: "Een korset dragen voor esthetiek, lichaamsbewustzijn of licht waist training-effect. Vereist goede pasvorm en regelmatige check-ins.",
  },
  {
    id: "penisring_cockring",
    name: "Penisring / cockring dragen",
    category: "appearance",
    level: 1,
    description: "Een ring of band om de penis dragen. Kan bloedstroom beïnvloeden en sensaties versterken. Gebruik juiste maat en draag niet langer dan aanbevolen.",
  },
  {
    id: "erotisch_dansen_prive",
    name: "Erotisch dansen (privé)",
    category: "appearance",
    level: 1,
    description: "Sensueel of erotisch dansen voor je partner in een privé-omgeving. Laagdrempelig en intiem.",
  },
  {
    id: "kleding_commando",
    name: "Kledingregels / verplicht kleden",
    category: "appearance",
    level: 2,
    description: "De Dom bepaalt wat de sub draagt. Kan gaan van specifieke ondergoed-regels tot volledige outfitkeuze. Onderdeel van D/s-protocol.",
  },
  {
    id: "leren_kleding_dragen",
    name: "Leren kleding dragen",
    category: "appearance",
    level: 2,
    description: "Leer als kledingmateriaal dragen — broeken, bustiers, harnasen. Combinatie van esthetiek en fetish.",
  },
  {
    id: "rubber_latex_kleding",
    name: "Rubber / latex kleding dragen",
    category: "appearance",
    level: 2,
    description: "Latex of rubber kleding dragen. Vereist speciale verzorging (shiners, talkpoeder). Let op latex-allergieën.",
  },
  {
    id: "uitdagende_kleding_prive",
    name: "Uitdagende / hoerige kleding (privé)",
    category: "appearance",
    level: 2,
    description: "Op verzoek uitdagende, seksueel getinte kleding dragen in privé-setting. Onderdeel van spel of protocol.",
  },
  {
    id: "verplicht_nudisme_prive",
    name: "Verplicht nudisme (privé)",
    category: "appearance",
    level: 2,
    description: "Naakt zijn op commando of als huisregel in de privéomgeving. Kwetsbaarheid als D/s-element.",
  },
  {
    id: "korset_middelafname",
    name: "Korset met waist training",
    category: "appearance",
    level: 3,
    description: "Langdurig of intensief korsetten met als doel middelvormverandering. Vereist graduele opbouw, regelmatige pauzes en lichamelijke check-ins.",
  },
  {
    id: "uitdagende_kleding_publiek",
    name: "Uitdagende kleding (publiek)",
    category: "appearance",
    level: 3,
    description: "Uitdagende kleding dragen in het openbaar. Combineert exhibitionisme met D/s-controle. Zorg voor juridische grenzen en toestemming van omstanders.",
  },
  {
    id: "verplicht_nudisme_publiek",
    name: "Verplicht nudisme (publiek / club)",
    category: "appearance",
    level: 3,
    description: "Naakt zijn in een publieke of semi-publieke omgeving (nudistenclub, BDSM-party). Alleen op daarvoor bestemde plekken.",
  },
  {
    id: "erotisch_dansen_publiek",
    name: "Erotisch dansen (publiek / voor anderen)",
    category: "appearance",
    level: 3,
    description: "Erotisch dansen voor een publiek op aanwijzing van de Dom. Combineert exhibitionisme en gehoorzaamheid.",
  },

  // ─── Crossdressing ────────────────────────────────────────────────────────
  {
    id: "crossdressing_mtf",
    name: "Crossdressing man → vrouw",
    category: "appearance",
    level: 2,
    description: "Een man kleedt zich als vrouw — lingerie, jurk, make-up, pruik. Kan feminisatie-element bevatten of puur esthetisch zijn. Communiceer wat het voor beiden betekent.",
  },
  {
    id: "crossdressing_ftm",
    name: "Crossdressing vrouw → man",
    category: "appearance",
    level: 2,
    description: "Een vrouw kleedt zich als man of met mannelijke attributen. Kan onderdeel zijn van rollenspel, genderplay of persoonlijke expressie.",
  },

  // ─── Ageplay & Little Space ───────────────────────────────────────────────
  {
    id: "little_speelgoed",
    name: "Knuffels en speelgoed in de scène",
    category: "adult_ageplay",
    level: 1,
    description: "Knuffeldieren, speelgoed of kinderlijke voorwerpen als comfort-anker in een scène. Laagdrempelig en vaak onderdeel van aftercare.",
  },
  {
    id: "ddlg_mdlb_dynamiek",
    name: "Daddy/Mommy Dom — little dynamiek",
    category: "adult_ageplay",
    level: 2,
    description: "Een zorgzame, dominante rol (DD/DM) tegenover een little-rol. Gebaseerd op vertrouwen en geborgenheid. Niet seksueel van aard tenzij beide partijen dit expliciet wensen.",
  },
  {
    id: "little_space",
    name: "Little space / leeftijdsspel (tiener)",
    category: "adult_ageplay",
    level: 2,
    description: "In een jongere mindset gaan (little space). Kan speels, onschuldig of D/s-geladen zijn. Altijd tussen volwassenen en volledig consensueel.",
  },
  {
    id: "baby_infantiliteit",
    name: "Baby / infantiliteit",
    category: "adult_ageplay",
    level: 3,
    description: "Rol aannemen van een baby of peuter — babytaal, fles, fopspeen. Een intens regressief spel dat veel vertrouwen en duidelijke grenzen vereist.",
  },
  {
    id: "fopspeen_fles",
    name: "Fopspeen / babyfles gebruiken",
    category: "adult_ageplay",
    level: 3,
    description: "Fopspeen of babyfles als prop in little space of ageplay. Comfort-object met sterke regressieve lading.",
  },
  {
    id: "luiers_dragen",
    name: "Luiers dragen",
    category: "adult_ageplay",
    level: 3,
    description: "Het dragen van een luier als onderdeel van ageplay of controle-dynamiek. Sterk regressief element; vereist hygiëne-afspraken en open communicatie.",
  },
  {
    id: "luiers_gebruik",
    name: "Luiers daadwerkelijk gebruiken",
    category: "adult_ageplay",
    level: 4,
    description: "Luiers ook daadwerkelijk gebruiken (plassen, poepen) als onderdeel van extreme ageplay of vernedering. Vergaande hygiëne-afspraken en clean-up protocol vereist.",
  },

  // ─── Pet Play (gedetailleerd) ──────────────────────────────────────────────
  {
    id: "petplay_collar_id",
    name: "Pet collar (identiteitsband)",
    category: "pet_play",
    level: 1,
    description: "Een halsband dragen als symbool van je pet-identiteit, los van bondage. Subtiel draagbaar en emotioneel betekenisvol.",
  },
  {
    id: "petplay_puppy",
    name: "Puppyplay",
    category: "pet_play",
    level: 2,
    description: "De rol van een hond aannemen — gedrag, geluiden en interacties. Vereist duidelijke in/out-scene cues en communicatie over grenzen.",
  },
  {
    id: "petplay_kitten",
    name: "Kittenplay",
    category: "pet_play",
    level: 2,
    description: "De rol van een kat aannemen — sierlijk, speels, soms weerbarstig. Populair in het BDSM-spectrum voor zijn combinatie van schattigheid en zelfstandigheid.",
  },
  {
    id: "petplay_pony",
    name: "Ponyplay",
    category: "pet_play",
    level: 2,
    description: "De rol van een paard aannemen — rijden, africhten, optredens. Kan uitgebreide uitrusting omvatten (bit, zweep, tuig).",
  },
  {
    id: "petplay_harnas",
    name: "Pet harnas / neus",
    category: "pet_play",
    level: 2,
    description: "Een dierlijk harnas of neus dragen als prop voor pet play. Versterkt de rol-immersie.",
  },
  {
    id: "petplay_oortjes",
    name: "Dierenoren / oortjes dragen",
    category: "pet_play",
    level: 2,
    description: "Huisdierenoortjes dragen als visueel pet play-element. Laagdrempelig en geschikt als instap tot de pet play-wereld.",
  },
  {
    id: "petplay_leiband",
    name: "Leiband / riem",
    category: "pet_play",
    level: 2,
    description: "Aan een leiband geleid worden als pet. Combineert bondage-element met pet play-dynamiek.",
  },
  {
    id: "petplay_geluiden",
    name: "Blaffen / miauwen / hinnikken",
    category: "pet_play",
    level: 2,
    description: "Communiceren via dierengeluiden terwijl in rol. Volledige immersie in pet space; menselijke taal (tijdelijk) loslaten.",
  },
  {
    id: "petplay_kom",
    name: "Eet- en drinkkom",
    category: "pet_play",
    level: 2,
    description: "Eten en drinken uit een kom op de grond als pet. Versterkt het onderdanige karakter van de rol.",
  },
  {
    id: "fox_tail_plug",
    name: "Vossenstaart / dierstaart butt plug",
    category: "pet_play",
    level: 3,
    description: "Een dierstaart dragen via een butt plug — vos, kat, hond. Combineert anaal spel met pet play-esthetiek. Gebruik altijd een plug met brede voet.",
  },
  {
    id: "petplay_kooi",
    name: "Bench / kooi / mand",
    category: "pet_play",
    level: 3,
    description: "Verblijven in een kooi, bench of mand als pet. Versterkt opsluiting en pet-identiteit. Zorg voor comfort en veiligheidsprotocol.",
  },
  {
    id: "petplay_kattenbak",
    name: "Kattenbak gebruik",
    category: "pet_play",
    level: 4,
    description: "Een kattenbak gebruiken als pet. Intensief vernedering/ageplay-element. Strikte hygiëneafspraken vereist.",
  },

  // ─── Bondage (uitbreiding) ─────────────────────────────────────────────────
  {
    id: "gag_opblaasbaar",
    name: "Mondknevel (opblaasbaar)",
    category: "bondage",
    level: 2,
    description: "Een opblaasbare mondknevel die de mond volledig vult. Verwijder onmiddellijk bij ademnood. Nooit alleen gebruiken.",
  },
  {
    id: "gag_penisvorm",
    name: "Mondknevel (penisvormig)",
    category: "bondage",
    level: 2,
    description: "Een penisvormige mondknevel met sterke vernedering-component. Communiceer verwachtingen rondom misselijkheid en ademhaling.",
  },
  {
    id: "gag_rubber",
    name: "Mondknevel (rubber)",
    category: "bondage",
    level: 2,
    description: "Rubberen mondknevel in diverse vormen. Comfortabeler dan acryl maar vereist check op rubber-allergie.",
  },
  {
    id: "borsten_afbinden",
    name: "Borsten afbinden",
    category: "bondage",
    level: 3,
    description: "Borsten afbinden met touw of band. Kan sensaties verhogen maar ook circulatie beïnvloeden. Max. 20-30 minuten; let op verkleuring en temperatuurverlies.",
  },
  {
    id: "gasmasker",
    name: "Gasmasker",
    category: "bondage",
    level: 3,
    description: "Een gasmasker dragen — sensory deprivation voor zicht en geluid gecombineerd. Controleer luchtstroom zorgvuldig.",
  },
  {
    id: "suspension_rechtop",
    name: "Ophangen (rechtop)",
    category: "bondage",
    level: 3,
    description: "Rechtop ophangen met touw of riemen. Vereist kennis van veilige bindingspunten en circulatiecheck. Nooit alleen uitvoeren.",
  },
  {
    id: "suspension_ondersteboven",
    name: "Ophangen (ondersteboven)",
    category: "bondage",
    level: 4,
    description: "Ondersteboven ophangen. Intensief en risicovol — bloeddruk in hoofd stijgt snel. Maximaal enkele minuten; ervaren rigger vereist.",
  },
  {
    id: "suspension_horizontaal",
    name: "Ophangen (horizontaal)",
    category: "bondage",
    level: 4,
    description: "Horizontaal zwevend ophangen. Vereist meerdere ankerpunten en een ervaren rigger. Intense shibari-techniek.",
  },
  {
    id: "opsluiting_kooi",
    name: "Opsluiting in kooi",
    category: "bondage",
    level: 3,
    description: "Opgesloten worden in een kooi of krat. Combineert fysieke beperking met psychologische onderdanigheid. Zorg voor vluchtmogelijkheid en communicatie.",
  },
  {
    id: "opsluiting_donker",
    name: "Opsluiting in het donker",
    category: "bondage",
    level: 3,
    description: "Opgesloten zijn in een volledig donkere ruimte. Intensieve sensory deprivation. Check op claustrofobie en paniekaanvallen.",
  },
  {
    id: "opsluiting_kleine_ruimte",
    name: "Opsluiting in kleine ruimte",
    category: "bondage",
    level: 3,
    description: "Beperkt worden tot een kleine ruimte (kast, kooi). Claustrofobie-check vereist. Altijd met communicatiemiddel of safeword-signaal.",
  },

  // ─── Power Exchange (uitbreiding) ─────────────────────────────────────────
  {
    id: "knielen_ritueel",
    name: "Knielen (als houding / ritueel)",
    category: "rituals",
    level: 1,
    description: "Knielen voor de Dom als teken van onderdanigheid of als beginritueel. Symbolisch maar krachtig. Zorgvuldige kniebescherming bij langdurig knielen.",
  },
  {
    id: "in_de_hoek_staan",
    name: "In de hoek staan",
    category: "discipline",
    level: 1,
    description: "Als straf of ritueel in de hoek staan, nadenken over gedrag. Klassiek D/s-element met psychologische werking.",
  },
  {
    id: "rituelen_protocols",
    name: "Rituelen en dagelijkse protocollen",
    category: "rituals",
    level: 2,
    description: "Vaste rituelen en protocollen in de D/s-relatie — aanspreekvorm, houding, dagelijkse taken. Structuur als fundament van de dynamiek.",
  },
  {
    id: "straf_standjes",
    name: "Strafstandjes / strafhouding",
    category: "discipline",
    level: 2,
    description: "Specifieke lichaamshoudingen als straf of correctie. Kan vermoeiend zijn; check belastbaarheid van gewrichten.",
  },
  {
    id: "spreekverbod",
    name: "Spreekvrijheid beperken",
    category: "power",
    level: 2,
    description: "Regels rond wanneer en wat de sub mag zeggen. Kan aanspreekvorm, onderwerpkeuze of totaal spreekverbod zijn.",
  },
  {
    id: "oogcontact_beperkingen",
    name: "Oogcontact beperkingen",
    category: "power",
    level: 2,
    description: "Regels rond oogcontact — vermijden, zoeken, of enkel op toestemming. Subtiel maar impactvol D/s-element.",
  },
  {
    id: "dienen_als_meubel",
    name: "Dienen als meubel (furniture play)",
    category: "power",
    level: 3,
    description: "De sub fungeert als levend meubel — voetenbankje, tafel, kapstok. Vergaande objectificatie met strikte communicatieafspraken.",
  },
  {
    id: "badkamer_controle",
    name: "Badkamergebruik controleren",
    category: "power",
    level: 3,
    description: "De Dom controleert wanneer de sub naar het toilet mag. Intensieve controle-dynamiek; afspraken over duur en gezondheid zijn essentieel.",
  },
  {
    id: "dienen_asbak",
    name: "Dienen als asbak (menselijke asbak)",
    category: "power",
    level: 4,
    description: "De sub fungeert als asbak. Uiterst ver in vernedering en vraagt expliciete instemming, brandwondpreventie en nuchter toezicht.",
  },
  {
    id: "lifestyle_247",
    name: "24/7 lifestyle D/s",
    category: "power",
    level: 4,
    description: "D/s-dynamiek die het volledige dagelijks leven omvat, ook buiten scènes. Vereist intensieve communicatie, wederzijds vertrouwen en regelmatige heronderhandeling.",
  },

  // ─── Sensation Play (uitbreiding) ─────────────────────────────────────────
  {
    id: "tepelklemmen_zacht",
    name: "Tepelklemmen (zacht)",
    category: "sensation",
    level: 2,
    description: "Zachte tepelklemmen voor milde pijn en sensuele druk. Begin met korte draagtijden. Verwijder bij gevoelloosheid of blauwverkleuring.",
  },
  {
    id: "tepelklemmen_hard",
    name: "Tepelklemmen (hard / Clover-type)",
    category: "sensation",
    level: 3,
    description: "Zware of Clover-klemmen die aanspannen bij trekken. Intensieve pijn; max. 10-15 minuten. Het verwijderen kan pijnlijker zijn dan het plaatsen.",
  },
  {
    id: "tepelgewichten",
    name: "Tepelgewichten",
    category: "sensation",
    level: 3,
    description: "Gewichten aan tepelklemmen hangen. Combinatie van aanhoudende pijn en bewegingssensatie. Zorgvuldige check op circulatie.",
  },
  {
    id: "geslacht_klemmen",
    name: "Geslachtsdelen klemmen",
    category: "sensation",
    level: 3,
    description: "Klemmen op geslachtsdelen (labia, scrotum). Intensief en intiem; korte draagtijden en regelmatige checks.",
  },
  {
    id: "geslacht_gewichten",
    name: "Geslachtsdelen gewichten",
    category: "sensation",
    level: 4,
    description: "Gewichten aan geslachtsdelen hangen. Vergaande pijnsensatie; alleen met ervaren partner en korte sessies.",
  },
  {
    id: "fire_cupping",
    name: "Fire cupping",
    category: "sensation",
    level: 3,
    description: "Glazen cups op de huid plaatsen via vacuüm door vlammen. Zuigende sensatie en markering. Vereist kennis van techniek; nooit op de wervelkolom.",
  },
  {
    id: "celpopping",
    name: "Celpopping",
    category: "sensation",
    level: 3,
    description: "Kleine huidbellen creëren door subcutane injecties. Tijdelijk effect. Vereist steriele techniek en medische basiskennis.",
  },
  {
    id: "naaldjes_borst_buik",
    name: "Naaldjes borst / buik / rug",
    category: "sensation",
    level: 3,
    description: "Artistieke naaldjes in niet-intieme zones. Steriele wegwerpnaalden; kennis van anatomie vereist om zenuwen en vaten te vermijden.",
  },
  {
    id: "naaldjes_intiem",
    name: "Naaldjes geslacht / tepels",
    category: "sensation",
    level: 4,
    description: "Naaldjes in geslachtsdelen of tepels. Intensief en riskant — uitsluitend met grondige kennis van anatomie en perfecte sterilisatie.",
  },
  {
    id: "artistiek_snijden",
    name: "Artistiek snijden (niet permanent)",
    category: "sensation",
    level: 4,
    description: "Oppervlakkige huidincisies als ritueel of esthetiek, bedoeld om te genezen. Steriele scalpel of lancet; kennis van wondheling essentieel.",
  },
  {
    id: "violet_wand_basis",
    name: "Violet Wand (niet intiem)",
    category: "sensation",
    level: 2,
    description: "Violet wand op armen, rug, benen — een elektrisch tintelende staf. Veilig als je pacemakers/metalen implantaten uitsluit. Vermijd hoofd en hart.",
  },
  {
    id: "violet_wand_tepels",
    name: "Violet Wand (borsten / tepels)",
    category: "sensation",
    level: 3,
    description: "Violet wand op borsten en tepels — intense tintelende pijn. Korte pulsen; check continue op huidreactie.",
  },
  {
    id: "violet_wand_intiem",
    name: "Violet Wand (intiem / geslacht)",
    category: "sensation",
    level: 3,
    description: "Violet wand op geslachtsdelen. Intensief en gevoelig; extra voorzichtigheid met slijmvliezen. Nooit intern gebruiken.",
  },
  {
    id: "powerbox_basis",
    name: "E-stim / TENS unit (niet intiem)",
    category: "sensation",
    level: 3,
    description: "Elektrische stimulatie via TENS-electrodes op ledematen of rug. Bewezen veilig mits correct gebruik; vermijd borst en hoofd.",
  },
  {
    id: "powerbox_intiem",
    name: "E-stim intiem",
    category: "sensation",
    level: 4,
    description: "Elektrische stimulatie op geslachtsdelen via speciaal e-stim speelgoed. Gebruik alleen daarvoor ontworpen apparaten. Nooit via zelfgemaakte circuits.",
  },
  {
    id: "shockcollar_prive",
    name: "Shockcollar (privé gebruik)",
    category: "sensation",
    level: 3,
    description: "Een shockcollar dragen die de Dom op afstand kan activeren. Psychologisch en fysiek element; stel intensiteit in op laagste werkende niveau.",
  },
  {
    id: "shockcollar_publiek",
    name: "Shockcollar (publiek / buiten scène)",
    category: "sensation",
    level: 4,
    description: "Shockcollar dragen in het openbaar met de Dom aan de controle. Vergaande controle-dynamiek; duidelijke grenzen rondom gebruik in sociale situaties.",
  },

  // ─── Impact Play (uitbreiding) ─────────────────────────────────────────────
  {
    id: "over_de_knie",
    name: "Over-de-knie (OTK billenkoek)",
    category: "impact",
    level: 1,
    description: "Klassieke positie waarbij de sub over de schoot ligt voor een billenkoek. Intiem en toegankelijk als instap in impact play.",
  },
  {
    id: "rubber_zweep_slapper",
    name: "Rubbere zweep / slapper",
    category: "impact",
    level: 2,
    description: "Rubberen zweep of slapper geeft een scherpe, oppervlakkige klap. Minder risico op diepe kneuzingen dan leer; goede keuze voor impact-beginners.",
  },
  {
    id: "fire_flogger",
    name: "Fire flogger",
    category: "impact",
    level: 3,
    description: "Flogger die in brand wordt gestoken voor vuureffect. Vereist brandveiligheidsprotocol: brandblusser, emmer water, geen synthetische kleding, ervaren topper.",
  },
  {
    id: "bullwhip",
    name: "Bullwhip / lange zweep",
    category: "impact",
    level: 4,
    description: "Lange zweep met hoge snelheid en kraakgeluid. Vereist veel ruimte en uitgebreide oefening; risico op huidbeschadiging en oogletsel bij omstanders.",
  },

  // ─── Fetishes (uitbreiding) ────────────────────────────────────────────────
  {
    id: "geur_scent_fetish",
    name: "Geur / scent fetisj",
    category: "materials_scent",
    level: 1,
    description: "Opgewonden worden door geur — huid, haar, zweet, parfum of kleding. Puur zintuiglijk en intiem.",
  },
  {
    id: "hoge_hakken_aanbidding",
    name: "Hoge hakken aanbidding",
    category: "body_focus",
    level: 1,
    description: "Erotische fixatie op hoge hakken — kijken, kussen, dragen of aanraken. Klassiek schoen- en voetenfetish-element.",
  },
  {
    id: "vagina_aanbidding",
    name: "Vagina-aanbidding",
    category: "body_focus",
    level: 1,
    description: "Gerichte aandacht en verering van de vagina als object van aanbidding. Onderdeel van lichaamsworship of femdom-dynamiek.",
  },
  {
    id: "footjob",
    name: "Footjob",
    category: "body_focus",
    level: 2,
    description: "Genitale stimulatie met de voeten. Populair in voeten- en lichaamsworship-kringen. Vraagt enige behendigheid en fijngevoeligheid.",
  },
  {
    id: "voetgeur",
    name: "Voetgeur / foot sniffing",
    category: "body_focus",
    level: 2,
    description: "Opwinding door het ruiken aan voeten of sokken van de partner. Geurcomponent van voetenfetish — kan gecombineerd worden met worship of onderdanigheid.",
  },
  {
    id: "trampling_voeten",
    name: "Trampling (voeten)",
    category: "body_focus",
    level: 2,
    description: "Belopen of betreden worden door de partner, met blote voeten, sokken of schoenen. Combinatie van voetenfetish en lichte pijnsensatie. Check gewicht en kwetsbare lichaamsdelen.",
  },
  {
    id: "voeten_in_gezicht",
    name: "Voeten in gezicht",
    category: "body_focus",
    level: 2,
    description: "Voeten op het gezicht van de sub — rustend, duwend of controlerend. Krachtig vernedering- en dominantie-element binnen voetenfetish.",
  },
  {
    id: "voeten_in_mond",
    name: "Voeten / tenen in mond",
    category: "body_focus",
    level: 2,
    description: "Tenen of voeten in de mond nemen — zuigen, likken. Diepere vorm van voetaanbidding, vereist hygiëne en wederzijdse bereidheid.",
  },
  {
    id: "voet_vernedering",
    name: "Voet-vernedering",
    category: "body_focus",
    level: 3,
    description: "Gebruikt worden als voetenbankje, uitgescholden worden terwijl je voeten aanbidt, of gedwongen worden op handen en knieën te kruipen voor voeten. Intensief vernedering-D/s-element.",
  },
  {
    id: "voetslaaf",
    name: "Voetslaaf / permanent foot service",
    category: "body_focus",
    level: 3,
    description: "Permanente of langdurige rol als voetslaaf — altijd beschikbaar voor massage, worship of gebruik. TPE-adjacent; duidelijke grenzen en periodieke check-ins noodzakelijk.",
  },
  {
    id: "laarzen_aanbidding",
    name: "Laarzen / schoenaanbidding",
    category: "body_focus",
    level: 2,
    description: "Laarzen of schoenen kussen, likken of aanbidden als onderdeel van voetenfetish of D/s-dynamiek.",
  },
  {
    id: "panty_sniffing",
    name: "Geur / panty sniffing",
    category: "materials_scent",
    level: 2,
    description: "Seksuele opwinding door het ruiken aan gedragen ondergoed. Geurspel in de voetenfetish- of lingeriefetish-sfeer.",
  },
  {
    id: "kniekousen_fetish",
    name: "Kniehousen / sokken fetisj",
    category: "materials_scent",
    level: 1,
    description: "Opgewonden worden door kniekousen of speciale sokken. Populair in combinatie met schoolmeisjes-ageplay of eenvoudige kledingfetisj.",
  },

  // ─── Fluid & Bodily (uitbreiding) ──────────────────────────────────────────
  {
    id: "watersports_geven",
    name: "Golden shower geven",
    category: "fluids",
    level: 2,
    description: "Plassen over partner als erotisch spel. Communiceer locatie, hygiëne en aftercare. Begin met een douche-omgeving voor gemak.",
  },
  {
    id: "watersports_ontvangen",
    name: "Golden shower ontvangen",
    category: "fluids",
    level: 3,
    description: "Plassen over worden door partner ontvangen. Kan deel zijn van vernedering of intimiteit. Duidelijke grenzen rondom mond/gezicht.",
  },
  {
    id: "urine_intiem",
    name: "Urine in mond / slikken",
    category: "fluids",
    level: 4,
    description: "Urine oraal ontvangen of doorslikken. Intensief vernedering-element. Gezondheidsrisico's bij infecties; check gezondheidsstatus van partner.",
  },
  {
    id: "plas_merken",
    name: "Plas-merken / territoriummarkering",
    category: "fluids",
    level: 3,
    description: "Urineren op partner als eigendomsbewijs of territoriummarkering. Krachtig D/s-element — spreek duidelijk af op welke lichaamsdelen en in welke context.",
  },
  {
    id: "plas_desperation",
    name: "Plas-controle / desperation",
    category: "fluids",
    level: 2,
    description: "Ophouden met plassen op bevel of totdat de dom toestemming geeft. Controle-element met lichte medische grens — niet te lang ophouden.",
  },
  {
    id: "buiten_plassen",
    name: "Buiten plassen / exhibitionistisch urineren",
    category: "fluids",
    level: 2,
    description: "Plassen buiten of op een semi-publieke locatie als exhibitionistisch element. Risico op boetes; kies een veilige, afgelegen plek.",
  },
  {
    id: "plas_in_kleding",
    name: "Nat worden in kleding / gedwongen plassen",
    category: "fluids",
    level: 3,
    description: "Op bevel in je kleding plassen of gedwongen worden nat te worden. Vernedering- en controledynamiek — duidelijke aftercare en hygiëneafspraken vereist.",
  },
  {
    id: "plas_slaaf",
    name: "Plas-slaaf / toilet slave",
    category: "fluids",
    level: 4,
    description: "De sub fungeert als menselijk toilet voor de dom. Intensief TPE-element. Strikte gezondheidseisen; alleen met geverifieerde gezondheidsstatussen en expliciet safeword.",
  },
  {
    id: "bloed_play",
    name: "Bloed play",
    category: "fluids",
    level: 4,
    description: "Erotisch spel met bloed. Hoog risico op bloedoverdraagbare aandoeningen. Uitsluitend met getest, monogaam partner en steriele materialen.",
  },
  {
    id: "katheters_urethral",
    name: "Katheters / urethral play",
    category: "fluids",
    level: 3,
    description: "Katheter of sounds in de urethra inbrengen. Hoog risico op infectie; gebruik steriele, daarvoor geschikte sounds en ruim glijmiddel.",
  },
  {
    id: "klysma_reiniging",
    name: "Klysma (voor reiniging)",
    category: "fluids",
    level: 3,
    description: "Klysma voor anale reiniging vóór penetratiespel. Praktisch en hygiënisch; gebruik lauwwarm water en herhaal niet te vaak.",
  },
  {
    id: "klysma_straf",
    name: "Klysma (als straf / controle)",
    category: "fluids",
    level: 4,
    description: "Klysma als straf of controle-element. Intensief D/s-spel; let op buikpijn, overbelasting van darmen en retentietijd.",
  },

  // ─── Anal & Penetration (verdieping) ───────────────────────────────────────
  {
    id: "rimmen",
    name: "Rimmen",
    category: "penetration",
    level: 2,
    description: "Orale stimulatie van de anus, gevend of ontvangend. Intiem en intens gevoelig. Hygiëne vooraf en eventueel een beflapje verlagen de drempel en het risico.",
  },
  {
    id: "dubbele_penetratie",
    name: "Dubbele penetratie",
    category: "penetration",
    level: 3,
    description: "Gelijktijdige penetratie van twee openingen, met partners of speeltjes. Vraagt om ruime opwarming, veel glijmiddel en een rustig tempo. Communiceer doorlopend over comfort.",
  },
  {
    id: "anale_training",
    name: "Anale training (oprekken)",
    category: "penetration",
    level: 3,
    description: "Geleidelijk oprekken van de anus met oplopende maten, vaak over weken opgebouwd. Geduld is de techniek: nooit forceren, altijd glijmiddel, stop bij scherpe pijn.",
  },
  {
    id: "deepthroat",
    name: "Deepthroat / facefucking",
    category: "penetration",
    level: 3,
    description: "Diepe orale penetratie tot in de keel, van zelf gecontroleerd tot overgenomen tempo. Kokhalsreflex went met oefening. Een handsignaal als stopwoord is verplicht — praten gaat even niet.",
  },
  {
    id: "sounding",
    name: "Sounding (urethraal)",
    category: "penetration",
    level: 4,
    description: "Het inbrengen van gladde staafjes (sounds) in de plasbuis. Hooggevoelig randspel met reëel infectie- en beschadigingsrisico. Uitsluitend steriel materiaal, steriel glijmiddel en veel kennis.",
  },

  // ─── Power Exchange (verdieping) ────────────────────────────────────────────
  {
    id: "dirty_talk",
    name: "Dirty talk",
    category: "power",
    level: 1,
    description: "Expliciete, opwindende taal tijdens het spel — van fluisteren tot bevelen. Bespreek vooraf welke woorden aanslaan en welke juist killing zijn.",
  },
  {
    id: "titels_aanspreekvormen",
    name: "Titels & aanspreekvormen",
    category: "power",
    level: 1,
    description: "Vaste titels zoals Sir, Meester, Meesteres of prinses als teken van de dynamiek. Klein ritueel, groot effect. Spreek af wanneer ze gelden — alleen in de scène of ook daarbuiten.",
  },
  {
    id: "joi",
    name: "JOI (masturbatie-instructies)",
    category: "power",
    level: 2,
    description: "De dominant dicteert precies hoe, wanneer en in welk tempo de partner zichzelf aanraakt. Controle zonder aanraking; werkt ook op afstand. Duidelijke instructies zijn het halve werk.",
  },
  {
    id: "overstimulatie",
    name: "Overstimulatie",
    category: "power",
    level: 3,
    description: "Doorgaan met stimuleren ná het orgasme, wanneer alles hypergevoelig is. Intens en snel overweldigend — spreek een duidelijk stopsignaal af en bouw de duur langzaam op.",
  },
  {
    id: "geruineerd_orgasme",
    name: "Geruïneerd orgasme",
    category: "power",
    level: 3,
    description: "De stimulatie stopt exact op het punt van klaarkomen, zodat het orgasme leegloopt zonder bevrediging. Frustrerend bij ontwerp; hoort bij orgasmecontrole en vraagt om goede timing.",
  },
  {
    id: "keyholding",
    name: "Keyholding (sleutelhouder)",
    category: "power",
    level: 3,
    description: "Eén partner beheert letterlijk de sleutel van het kuisheidsapparaat van de ander. Langdurige machtsdynamiek; maak afspraken over duur, hygiënepauzes en een noodsleutel.",
  },
  {
    id: "free_use",
    name: "Free use dynamiek",
    category: "power",
    level: 4,
    description: "Vooraf gegeven toestemming om de partner op afgesproken momenten seksueel te gebruiken zonder vraag vooraf. Vergt ijzersterke kaders, heldere grenzen en een altijd geldig stopwoord.",
  },
  {
    id: "erotische_hypnose",
    name: "Erotische hypnose",
    category: "power",
    level: 4,
    description: "Trance en suggestie als spel met controle en overgave. Diep psychologisch; werk alleen met wederzijds vertrouwen, bespreek suggesties vooraf en bouw altijd een wek-signaal in.",
  },

  // ─── Fluid & Bodily (verdieping) ────────────────────────────────────────────
  {
    id: "breeding_creampie",
    name: "Breeding / creampie",
    category: "fluids",
    level: 2,
    description: "Klaarkomen in de partner, al dan niet met een bevruchtingsfantasie. Bespreek anticonceptie en soa-status expliciet — de fantasie is vrij, de biologie niet.",
  },
  {
    id: "snowballen",
    name: "Snowballen",
    category: "fluids",
    level: 2,
    description: "Sperma doorgeven met een kus na orale seks. Intiem vloeistofspel; soa-afspraken gelden hier net zo goed als bij andere uitwisseling.",
  },
  {
    id: "lactatie",
    name: "Lactatie / borstvoeding-spel",
    category: "fluids",
    level: 3,
    description: "Erotisch spel rond borstvoeding of geïnduceerde lactatie, vaak verweven met verzorgende dynamieken. Inductie vergt maanden toewijding; bespreek wat het emotioneel betekent.",
  },

  // ─── Bondage (verdieping) ───────────────────────────────────────────────────
  {
    id: "sleepsack",
    name: "Sleepsack",
    category: "bondage",
    level: 3,
    description: "Een lichaamszak van leer of latex die het hele lichaam omsluit. Totale bewegingsloosheid en zware sensorische inperking. Nooit alleen laten; let op temperatuur en ademruimte.",
  },
  {
    id: "predicament_bondage",
    name: "Predicament bondage",
    category: "bondage",
    level: 4,
    description: "Vastbinden in een houding waarin elke verlichting van de ene spanning een andere verergert — een duivels dilemma. Vereist ervaren rigging, korte sessies en scherp toezicht.",
  },
  {
    id: "vacuumbed",
    name: "Vacuümbed",
    category: "bondage",
    level: 4,
    description: "Tussen twee latexlagen vacuüm gezogen worden — volledige immobilisatie en sensatie over het hele lichaam. Ademhaling via buis of opening; nooit zonder continue supervisie.",
  },

  // ─── Role Play (verdieping) ─────────────────────────────────────────────────
  {
    id: "masseur_client",
    name: "Masseur / cliënt",
    category: "roleplay",
    level: 1,
    description: "Een massage die 'per ongeluk' steeds intiemer wordt. Laagdrempelig rollenspel met langzame opbouw en veel aanraking. Perfect als opwarmer voor meer.",
  },
  {
    id: "sekswerker_client",
    name: "Sekswerker / cliënt",
    category: "roleplay",
    level: 2,
    description: "Rollenspel rond betaalde seks — onderhandeling, transactie en vervreemding als kink. Spreek vooraf af wat de 'dienst' inhoudt en waar het spel eindigt.",
  },
  {
    id: "fantasy_monster",
    name: "Fantasy / monster",
    category: "roleplay",
    level: 2,
    description: "Rollenspel met niet-menselijke wezens — monsters, tentakels, mythische figuren. Pure verbeelding, vaak met speciaal speelgoed. Alles mag bestaan zolang beide spelers het script kennen.",
  },
  {
    id: "primal_play",
    name: "Primal (jagen & prooi)",
    category: "roleplay",
    level: 3,
    description: "Instinctief spel zonder woorden — jagen, worstelen, grommen, bijten. De prooi vlucht, de jager vangt. Fysiek intens; spreek vooraf een duidelijk stopsignaal af dat ook mid-worsteling werkt.",
  },
  {
    id: "somnofilie",
    name: "Somnofilie (consensueel slaapspel)",
    category: "roleplay",
    level: 4,
    description: "Gewekt worden met seksuele aanrakingen, of doen alsof je slaapt. Toestemming wordt hier vooraf gegeven, niet in het moment — leg de kaders vast wanneer beiden klaarwakker zijn.",
  },

  // ─── Uiterlijk & Kleding (verdieping) ───────────────────────────────────────
  {
    id: "body_writing",
    name: "Body writing",
    category: "appearance",
    level: 1,
    description: "Woorden of tekens op het lichaam schrijven — namen, titels, vernederingen of bezitsclaims. Gebruik huidvriendelijke stiften; de tekst wast weg, het gevoel blijft.",
  },
  {
    id: "maskers",
    name: "Maskers",
    category: "appearance",
    level: 2,
    description: "Maskers voor anonimiteit, transformatie of esthetiek — van venetiaans tot leer. Wie zijn gezicht verliest, wint een rol. Let op zicht en ademruimte bij gesloten modellen.",
  },
  {
    id: "sissificatie",
    name: "Sissificatie / feminisatie",
    category: "appearance",
    level: 3,
    description: "Gedwongen of gewenste feminisering als machtsspel — kleding, make-up, gedrag en aanspreekvormen. Kan vernederend of juist bevrijdend bedoeld zijn; bespreek welke van de twee het is.",
  },

  // ─── Exhibition & Voyeurism (verdieping) ────────────────────────────────────
  {
    id: "spiegelspel",
    name: "Spiegelspel",
    category: "exhibition",
    level: 1,
    description: "Seks of spel voor de spiegel — jezelf en elkaar zien als voyeur én exhibitionist tegelijk. Laagdrempelig en thuis te doen; de blik went, de spanning niet.",
  },
  {
    id: "remote_toy_publiek",
    name: "Op afstand bestuurbaar speeltje (publiek)",
    category: "exhibition",
    level: 2,
    description: "Een draagbaar speeltje dat de partner via een app bedient terwijl je samen buiten bent. Publieke spanning zonder publiek risico — kies stille speeltjes en discrete locaties.",
  },
  {
    id: "filmen_prive",
    name: "Filmen / eigen opnames",
    category: "exhibition",
    level: 3,
    description: "Jezelf en elkaar filmen of fotograferen tijdens het spel, om terug te kijken of voor de spanning van de lens. Maak harde afspraken over opslag, bewaartermijn en verwijderen — beelden zijn voor altijd.",
  },
  {
    id: "trio_groepsseks",
    name: "Trio / groepsseks",
    category: "exhibition",
    level: 3,
    description: "Seks met drie of meer — van trio tot groepsspel. Bekeken worden en kijken zit ingebakken. Bespreek vooraf grenzen per persoon, soa-afspraken en wat het voor de eigen relatie betekent.",
  },
  {
    id: "glory_hole",
    name: "Glory hole",
    category: "exhibition",
    level: 4,
    description: "Anonieme seksuele handelingen door een opening in een wand. Anonimiteit als kink; de risico's zijn navenant. Soa-bescherming is niet onderhandelbaar, afspraken vooraf evenmin.",
  },

  // ─── Aanbidding & Worship (verdieping) ──────────────────────────────────────
  {
    id: "cock_worship",
    name: "Cock worship",
    category: "body_focus",
    level: 2,
    description: "Toegewijde, langdurige aanbidding van de penis — oraal, met handen, met woorden. Geen doelgerichte seks maar een ritueel van devotie en dominantie.",
  },
  {
    id: "ass_worship",
    name: "Ass worship",
    category: "body_focus",
    level: 2,
    description: "Aanbidding van billen — kussen, likken, masseren, ertegen aanliggen, facesitting-licht. Vaak verweven met dominantie van degene die aanbeden wordt.",
  },

  // ─── Sensation Play (verdieping) ────────────────────────────────────────────
  {
    id: "voedselspel",
    name: "Voedselspel / sploshing",
    category: "sensation",
    level: 2,
    description: "Spelen met voedsel op het lichaam — slagroom, chocolade, of volledig sploshing met natte, kliederige substanties. Leg handdoeken klaar en houd suiker weg bij slijmvliezen.",
  },
  {
    id: "fear_play",
    name: "Fear play",
    category: "sensation",
    level: 3,
    description: "Bewust angst opwekken als spel — dreiging, verrassing, duisternis, messen die nooit snijden. De adrenaline is echt, het gevaar niet. Aftercare is hier geen optie maar een vereiste.",
  },
  {
    id: "figging",
    name: "Figging (gember)",
    category: "sensation",
    level: 3,
    description: "Een geschilde gemberwortel anaal of vaginaal inbrengen voor een intense, brandende sensatie. Ouderwets straf-element; de branding piekt na minuten en is niet weg te spoelen — doseer klein.",
  },
  {
    id: "ballbusting",
    name: "Ballbusting / CBT-impact",
    category: "sensation",
    level: 4,
    description: "Slaan, tikken of drukken op de testikels als pijnspel. Klein doelwit, groot risico — begin extreem licht, vermijd torsie en stop direct bij misselijkheid of doffe napijn.",
  },

  // ─── Impact Play (verdieping) ───────────────────────────────────────────────
  {
    id: "body_slapping",
    name: "Body slapping",
    category: "impact",
    level: 2,
    description: "Slaan met de vlakke hand op vlezige zones — dijen, billen, borst. Directer en intiemer dan speeltjes. Blijf weg van nieren, wervelkolom en gewrichten.",
  },

  // ─── Straf & Correctie ──────────────────────────────────────────────────────
  // Straf corrigeert afgesproken gedrag — nooit straffen om het straffen.
  {
    id: "strafregels_schrijven",
    name: "Strafregels schrijven",
    category: "discipline",
    level: 1,
    description: "De overtreden regel een afgesproken aantal keer uitschrijven, met de hand. Klassiek en reflectief: de herhaling prent de regel in. De correctie zit in het herinneren, niet in het vernederen.",
  },
  {
    id: "verplichte_reflectie",
    name: "Reflectie & excuses",
    category: "discipline",
    level: 1,
    description: "Opschrijven of uitspreken wat er misging, waarom de regel bestaat en hoe het anders gaat. De mildste en vaak effectiefste correctie — gedrag verandert door begrip, niet door pijn.",
  },
  {
    id: "privileges_intrekken",
    name: "Privileges intrekken",
    category: "discipline",
    level: 1,
    description: "Tijdelijk verlies van een afgesproken voorrecht — de bank in plaats van de schoot, geen toetje, geen telefoon in de avond. Duur en reden vooraf helder; het privilege keert terug zodra de les geleerd is.",
  },
  {
    id: "strafklusjes",
    name: "Strafklusjes",
    category: "discipline",
    level: 1,
    description: "Extra huishoudelijke taken als correctie — zilver poetsen, de vloer op handen en knieën. Nuttig én corrigerend. Koppel de klus zichtbaar aan de overtreding, anders is het gewoon huishouden.",
  },
  {
    id: "speeltijd_ontzegd",
    name: "Speeltijd ontzegd",
    category: "discipline",
    level: 1,
    description: "Een geplande scène of speelmoment vervalt als gevolg van een overtreding. Raakt precies waar de dynamiek leeft. Wees zuinig met deze straf — wie te vaak niets te verliezen heeft, stopt met proberen.",
  },
  {
    id: "avondklok_straf",
    name: "Avondklok / vroeg naar bed",
    category: "discipline",
    level: 1,
    description: "Eerder naar bed of binnen blijven als correctie, met vaste duur. Structuur-straf zonder fysiek element. Werkt alleen als de reden benoemd is en het gewone leven (werk, afspraken) buiten schot blijft.",
  },
  {
    id: "opgelegde_stilte",
    name: "Opgelegde stilte",
    category: "discipline",
    level: 2,
    description: "Een afgebakende periode niet mogen spreken na een overtreding — de mond die de regel brak, rust even. Spreek een non-verbaal veiligheidssignaal af; een straf mag nooit het stopwoord blokkeren.",
  },
  {
    id: "strafoefeningen",
    name: "Strafoefeningen (fysiek)",
    category: "discipline",
    level: 2,
    description: "Squats, planken of wandzitten als corrigerende inspanning, met een vooraf bepaald aantal. Vermoeidheid als leermoment. Ken de fysieke grenzen en blessuregeschiedenis van wie de oefening doet.",
  },
  {
    id: "orgasme_uitstel_straf",
    name: "Orgasme-uitstel als straf",
    category: "discipline",
    level: 2,
    description: "Een afgesproken aantal dagen geen orgasme na een overtreding. Correctie via verlangen in plaats van pijn. Duur vooraf vastgelegd — onbepaald uitstel is geen straf maar een machtslek.",
  },
  {
    id: "strafspanking",
    name: "Strafspanking",
    category: "discipline",
    level: 2,
    description: "Een spanking als correctie: nuchter, geteld en afgebakend — geen erotisch spel maar een gevolg. Regel en aantal zijn vooraf bekend, woede diskwalificeert de gever, en na afloop volgt herstel en een schone lei.",
  },
  {
    id: "strafessay",
    name: "Strafessay",
    category: "discipline",
    level: 2,
    description: "Een opstel schrijven over de overtreden regel — waarom die bestaat, wat er misging, wat er verandert. Zwaarder dan regels schrijven: hier moet nagedacht worden. De Dom leest en bespreekt het na.",
  },
  {
    id: "mondzeep",
    name: "Mondzeep",
    category: "discipline",
    level: 3,
    description: "Een reep milde zeep kort in de mond als klassieke correctie voor verbale overtredingen. Ouderwets theater met echte risico's: alleen milde zeep, nooit doorslikken, kort houden en goed naspoelen.",
  },

  // ─── Rituelen & Training ────────────────────────────────────────────────────
  {
    id: "ochtend_avondritueel",
    name: "Ochtend- & avondritueel",
    category: "rituals",
    level: 1,
    description: "Een vast begin- en eindpunt van de dag binnen de dynamiek — een groet, een kniel-moment, een bericht op vaste tijd. Klein en herhaalbaar; het ritme draagt de dynamiek door drukke dagen heen.",
  },
  {
    id: "begroetingsritueel",
    name: "Begroetingsritueel",
    category: "rituals",
    level: 1,
    description: "Een vaste handeling bij thuiskomst of weerzien — knielen bij de deur, een kus op de hand, een vaste zin. Markeert de overgang van buitenwereld naar dynamiek.",
  },
  {
    id: "verantwoordingsdagboek",
    name: "Verantwoordingsdagboek",
    category: "rituals",
    level: 1,
    description: "De sub houdt een dagboek bij over taken, gevoelens en gehoorzaamheid, dat de Dom leest. Traint reflectie en geeft de Dom zicht op wat onuitgesproken blijft. Spreek af wat privé mag blijven.",
  },
  {
    id: "positietraining",
    name: "Positietraining",
    category: "rituals",
    level: 2,
    description: "Vaste houdingen aanleren die op commando aangenomen worden — wachten, presenteren, rusten. Herhaling bouwt lichaamsgeheugen. Bouw langzaam op en let op knieën, polsen en rug.",
  },
  {
    id: "wachttraining",
    name: "Wachttraining",
    category: "rituals",
    level: 2,
    description: "Leren wachten — stil, in positie, zonder aandacht op te eisen — tot de Dom beschikbaar is. Traint geduld en overgave. Begin met minuten, niet met uren, en houd zicht op comfort.",
  },
  {
    id: "diensttraining",
    name: "Diensttraining",
    category: "rituals",
    level: 2,
    description: "Het aanleren van perfecte, persoonlijke service — thee precies goed, kleding klaargelegd, anticiperen op behoeften. De training zit in de standaard: goed is niet genoeg, het moet zóals afgesproken.",
  },
  {
    id: "inspectie_ritueel",
    name: "Inspectie-ritueel",
    category: "rituals",
    level: 2,
    description: "Een terugkerend moment waarop de Dom lichaam, houding, kleding of taken keurt. Presentatie als ritueel; de blik van de keurende is het eigenlijke spel. Benoem vooraf wat gekeurd wordt.",
  },
  {
    id: "eetritueel",
    name: "Eetritueel (voeren)",
    category: "rituals",
    level: 2,
    description: "Gevoerd worden uit de hand, eten op aanwijzing of pas beginnen na toestemming. Zorg en controle in één gebaar. Het gaat om het ritueel, nooit om het beperken van voeding zelf.",
  },
  {
    id: "toestemmingsprotocol",
    name: "Toestemming vragen (protocol)",
    category: "rituals",
    level: 3,
    description: "Voor afgesproken handelingen eerst toestemming vragen — zitten, eten, klaarkomen, de kamer verlaten. Diepe dagelijkse controle. Baken scherp af welke situaties eronder vallen en welke nooit.",
  },
  {
    id: "spraakprotocol",
    name: "Spraakprotocol",
    category: "rituals",
    level: 3,
    description: "Vaste spreekregels als training — in de derde persoon spreken, zinnen beginnen met de titel van de Dom, of alleen spreken na aanraking. Houd het vol te leren; te complexe protocollen breken zichzelf.",
  },
  {
    id: "hoog_protocol",
    name: "Hoog protocol",
    category: "rituals",
    level: 3,
    description: "Afgebakende periodes waarin alle regels tegelijk gelden — houding, spraak, blik, beweging. Formeel en intens; niet vol te houden als levensstijl. Duidelijk begin- en eindsignaal is essentieel.",
  },
  {
    id: "orgasme_op_commando",
    name: "Orgasme op commando (training)",
    category: "rituals",
    level: 3,
    description: "Trainen om op een woord of signaal klaar te komen — conditionering over weken of maanden. Vraagt geduld en veel herhaling; vier de vooruitgang in plaats van het missen te bestraffen.",
  },
];

// Listings climb the ladder: beginner-kinks eerst, diepgaand als laatste. Stable
// sort, dus binnen één niveau blijft de handgekozen volgorde staan.
export function getKinksByCategory(category: string): Kink[] {
  return KINKS.filter((k) => k.category === category).sort((a, b) => a.level - b.level);
}

export function getKinksByCategoryAndLevel(category: string, maxLevel: number): Kink[] {
  return KINKS.filter((k) => k.category === category && k.level <= maxLevel).sort(
    (a, b) => a.level - b.level,
  );
}

export const LEVEL_MAX: Record<string, number> = {
  beginner:  1,
  gevorderd: 2,
  ervaren:   3,
  diepgaand: 4,
};
