import type { Kink } from "@/types";

// level 1 = beginner (kort)  |  2 = gevorderd (normaal)  |  3 = ervaren (lang)  |  4 = diepgaand (alles)
export const KINKS: Kink[] = [
  // ─── Impact Play ───────────────────────────────────────────────────────────
  {
    id: "spanking_hand",
    name: "Spanking (hand)",
    category: "Impact Play",
    level: 1,
    description: "Slaan met de hand op het zitvlak. Een van de meest toegankelijke impactspellen met directe feedback. Communiceer van tevoren de gewenste intensiteit.",
  },
  {
    id: "spanking_implement",
    name: "Spanking (implement)",
    category: "Impact Play",
    level: 2,
    description: "Slaan met een voorwerp zoals een spatel of paddle. Intensere sensaties dan met de hand, met meer controle over kracht en plek. Goede warming-up en aftercare zijn essentieel.",
  },
  {
    id: "flogging",
    name: "Flogging",
    category: "Impact Play",
    level: 2,
    description: "Zweepspel met meerdere leren of touwriemen (flogger). Kan variëren van zacht en sensueel tot intens. Vereist kennis van veilige zones op het lichaam.",
  },
  {
    id: "caning",
    name: "Caning",
    category: "Impact Play",
    level: 3,
    description: "Stokslagen met een dunne rietachtige stok. Scherpe, intense pijn die lang nawerkt. Vereist ervaring en kennis van veilige slagplaatsen.",
  },
  {
    id: "cropping",
    name: "Crop",
    category: "Impact Play",
    level: 2,
    description: "Gebruik van een rijzweep (crop) voor gerichte tikken. Preciezer dan flogging, goed te doseren. Populair in paardenspel en dominante dynamieken.",
  },
  {
    id: "paddling",
    name: "Paddling",
    category: "Impact Play",
    level: 2,
    description: "Slaan met een paddle (plat, stijf slagwerktuig). Geeft een diepe, dofige klap. Graduele opbouw van intensiteit is aan te raden.",
  },
  {
    id: "whipping",
    name: "Whipping",
    category: "Impact Play",
    level: 3,
    description: "Zweepspel met een lange, dunne zweep. Vereist techniek en afstandsinschatting. Alleen voor ervaren spelers vanwege risico op onbedoelde treffers.",
  },
  {
    id: "belt",
    name: "Belt",
    category: "Impact Play",
    level: 2,
    description: "Gebruik van een riem als slagwerktuig. Toegankelijk en vertrouwd aanvoelend. Communiceer duidelijk over intensiteit en gewenste plaatsen.",
  },
  {
    id: "slapping_face",
    name: "Face slapping",
    category: "Impact Play",
    level: 3,
    description: "Gezichtsklappen als daad van dominantie of vernedering. Vereist uitdrukkelijke toestemming en kennis van veilige technieken. Nooit hard of onverwacht.",
  },
  {
    id: "punching",
    name: "Punching / thuding",
    category: "Impact Play",
    level: 3,
    description: "Vuistslagen of druktechnieken op vlezig lichaamsweefsel (thudding). Diepe, botsbewegingen eerder dan scherpe pijn. Uitsluitend voor gevorderde spelers met anatomische kennis.",
  },
  {
    id: "trampling",
    name: "Trampling",
    category: "Impact Play",
    level: 3,
    description: "Lopen, staan of trappen op het lichaam van de partner. Vereist gewichtsverdeling en kennis van kwetsbare lichaamsdelen. Altijd met volledige toestemming en voorzichtigheid.",
  },

  // ─── Bondage ───────────────────────────────────────────────────────────────
  {
    id: "rope_bondage",
    name: "Rope bondage",
    category: "Bondage",
    level: 2,
    description: "Vastbinden met touw, waarbij de submissieve partner beperkt wordt in bewegingsvrijheid. Geeft een gevoel van controle en overgave. Leer altijd knippen voor noodgevallen.",
  },
  {
    id: "shibari",
    name: "Shibari / suspension",
    category: "Bondage",
    level: 4,
    description: "Japanse bindkunst waarbij touw esthetisch en sensueel om het lichaam wordt geweven. Suspensie (ophangen) is de meest gevorderde variant. Vereist uitgebreide training.",
  },
  {
    id: "handcuffs",
    name: "Handcuffs / metal cuffs",
    category: "Bondage",
    level: 1,
    description: "Metalen handboeien voor polsbeperking. Snel aan te leggen, maar kunnen bij verkeerde druk pijnlijk zijn. Houd altijd een sleutel bij de hand.",
  },
  {
    id: "leather_cuffs",
    name: "Leather cuffs",
    category: "Bondage",
    level: 1,
    description: "Leren manchetten voor pols of enkel. Comfortabeler dan metaal, geschikt voor langduriger gebruik. Een veelzijdige basis voor bondage.",
  },
  {
    id: "spreader_bar",
    name: "Spreader bar",
    category: "Bondage",
    level: 2,
    description: "Starre stang die armen of benen op afstand houdt. Geeft een gevoel van kwetsbaarheid en expositie. Comfortabele plek en tijdslimiet zijn belangrijk.",
  },
  {
    id: "hogtie",
    name: "Hogtie",
    category: "Bondage",
    level: 3,
    description: "Verbinden van polsen en enkels aan de achterkant van het lichaam. Intensieve positie die de bewegingsvrijheid volledig beperkt. Regelmatige check-ins zijn noodzakelijk.",
  },
  {
    id: "mummification",
    name: "Mummification",
    category: "Bondage",
    level: 4,
    description: "Het volledig inbakeren van het lichaam met tape, latex of stof. Geeft een intens gevoel van beperktheid en sensorische overweldiging. Nooit alleen uitvoeren.",
  },
  {
    id: "straitjacket",
    name: "Straitjacket",
    category: "Bondage",
    level: 4,
    description: "Dwangbuis die armen en torso fixeert. Symbool van volledige controle. Altijd een veilig signaal afspreken.",
  },
  {
    id: "chastity",
    name: "Chastity device",
    category: "Bondage",
    level: 3,
    description: "Kuisheidsapparaat dat seksuele activiteit beperkt. Onderdeel van orgasme- of seksuele controle. Hygiëne en regelmatige controle zijn essentieel.",
  },
  {
    id: "gag_ball",
    name: "Ball gag",
    category: "Bondage",
    level: 2,
    description: "Balknevel die spreken verhindert. Geeft een gevoel van stilte en overgave. Gebruik non-verbale safewords (kloppen, knijpen) als alternatief.",
  },
  {
    id: "gag_bit",
    name: "Bit gag",
    category: "Bondage",
    level: 2,
    description: "Bit-achtige knevel, vergelijkbaar met een paardenbijt. Laat meer speekselafvloed toe dan een balknevel. Gebruik non-verbale safewords.",
  },
  {
    id: "gag_tape",
    name: "Tape gag",
    category: "Bondage",
    level: 2,
    description: "Tape over de mond als knevel. Eenvoudig en visueel impactvol. Zorg dat de neusgangen vrij zijn en gebruik huidvriendelijke tape.",
  },
  {
    id: "blindfold",
    name: "Blindfold",
    category: "Bondage",
    level: 1,
    description: "Oogbedekking die zicht ontneemt. Vergroot andere zintuigen en het gevoel van kwetsbaarheid. Een toegankelijke introductie tot sensorische spelen.",
  },
  {
    id: "hood",
    name: "Hood / sensory deprivation hood",
    category: "Bondage",
    level: 3,
    description: "Kap over het hoofd die zicht en soms gehoor ontneemt. Intensief sensorisch hulpmiddel. Zorg altijd voor voldoende luchttoevoer.",
  },
  {
    id: "collar_leash",
    name: "Collar & leash",
    category: "Bondage",
    level: 1,
    description: "Halsband en riem als symbool van eigenaarschap en dynamiek. Kan puur symbolisch zijn of in actief spel gebruikt worden. Draag een veilige, juist passende halsband.",
  },

  // ─── Power Exchange ─────────────────────────────────────────────────────────
  {
    id: "dominance_submission",
    name: "D/s dynamic",
    category: "Power Exchange",
    level: 1,
    description: "Een consensuele dynamiek waarbij één persoon leidt (dominant) en de ander volgt (submissief). De basis van veel BDSM-relaties. Goede communicatie is de kern.",
  },
  {
    id: "master_slave",
    name: "Master / slave dynamic",
    category: "Power Exchange",
    level: 3,
    description: "Een intensievere D/s-dynamiek waarbij de submissieve partner uitgebreide controle overdraagt. Vereist diepe wederzijdse kennis en vertrouwen. Altijd grenzen en herziening afspreken.",
  },
  {
    id: "owner_pet",
    name: "Owner / pet dynamic",
    category: "Power Exchange",
    level: 2,
    description: "Een dynamiek waarbij één persoon de 'eigenaar' is en de ander zich als huisdier gedraagt. Kan speels en sensueel zijn. Inclusief non-verbale communicatie en beloningen.",
  },
  {
    id: "collaring",
    name: "Collaring ceremony",
    category: "Power Exchange",
    level: 3,
    description: "Een ceremoniële handeling waarbij een halsband overgedragen wordt als symbool van toewijding en eigenaarschap. Vergelijkbaar met een verloving binnen sommige BDSM-relaties.",
  },
  {
    id: "rules_protocols",
    name: "Rules & protocols",
    category: "Power Exchange",
    level: 2,
    description: "Het opstellen van regels, gewoonten en protocollen die de dynamiek structureren. Geeft duidelijkheid en richting. Bespreek regelmatig of regels nog passend zijn.",
  },
  {
    id: "punishment",
    name: "Punishment play",
    category: "Power Exchange",
    level: 2,
    description: "Straf als onderdeel van de dynamiek wanneer regels overtreden worden. Altijd consensueel en afgebakend. Onderscheid tussen straf en mishandeling is cruciaal.",
  },
  {
    id: "humiliation_verbal",
    name: "Verbal humiliation",
    category: "Power Exchange",
    level: 2,
    description: "Verbale vernedering, schelden of kleinerende uitspraken als onderdeel van spel. Vereist expliciete toestemming en kennis van triggers. Wat vernederend is, is persoonlijk.",
  },
  {
    id: "degradation",
    name: "Degradation",
    category: "Power Exchange",
    level: 3,
    description: "Diepgaande vernedering via taal, acties of situaties. Intensief en emotioneel geladen. Uitgebreide nabespreking is altijd nodig.",
  },
  {
    id: "praise_kink",
    name: "Praise kink",
    category: "Power Exchange",
    level: 1,
    description: "Opwinding door goedkeuring, lof en bevestiging. Het tegenovergestelde van vernedering, maar net zo krachtig. Toegankelijk en positief van aard.",
  },
  {
    id: "objectification",
    name: "Objectification",
    category: "Power Exchange",
    level: 3,
    description: "De ander behandelen als een object zonder eigen wil. Intensief en vraagt om volledig vertrouwen. Regelmatige check-ins zijn van belang.",
  },
  {
    id: "forced_orgasm",
    name: "Forced orgasm",
    category: "Power Exchange",
    level: 2,
    description: "Het afdwingen van een orgasme, ook als de partner dit probeert te weigeren. Vereist duidelijke toestemming en kennis van elkaars lichaam.",
  },
  {
    id: "orgasm_denial",
    name: "Orgasm denial / edging",
    category: "Power Exchange",
    level: 2,
    description: "Het herhaaldelijk opbouwen van opwinding zonder ontlading toe te staan. Vergroot seksuele spanning en controle. Communiceer over grenzen en duur.",
  },
  {
    id: "orgasm_control",
    name: "Orgasm control / permission",
    category: "Power Exchange",
    level: 2,
    description: "De dominant beslist wanneer, hoe of of de partner een orgasme mag hebben. Onderdeel van uitgebreidere machtsuitwisseling. Vereist wederzijdse communicatie.",
  },
  {
    id: "service",
    name: "Service (domestic / personal)",
    category: "Power Exchange",
    level: 1,
    description: "De submissieve partner verleent diensten (huishoudelijk, persoonlijk) als uiting van toewijding. Kan buiten seksuele contexten plaatsvinden. Grenzen gelden ook hier.",
  },
  {
    id: "financial_domination",
    name: "Financial domination",
    category: "Power Exchange",
    level: 4,
    description: "De submissieve partner draagt financiële controle over aan de dominant. Uiterst gevoelig gebied. Altijd met duidelijke grenzen en buiten staat van kwetsbaarheid bespreken.",
  },

  // ─── Role Play ──────────────────────────────────────────────────────────────
  {
    id: "cnc",
    name: "Consensual non-consent (CNC)",
    category: "Role Play",
    level: 3,
    description: "Consensuele non-consent — spelen met de fantasie van gedwongen seks, terwijl alles vooraf afgesproken is. Vereist intensieve voorbereiding en duidelijke safewords.",
  },
  {
    id: "interrogation",
    name: "Interrogation scene",
    category: "Role Play",
    level: 3,
    description: "Verhoor-scène waarbij één persoon informatie probeert te ontlokken via druk. Theatraal en spanningsvol. Sfeer en grenzen altijd van tevoren afbakenen.",
  },
  {
    id: "capture_scene",
    name: "Capture / kidnapping scene",
    category: "Role Play",
    level: 3,
    description: "Ontvoerings- of vangstscène. Adrenalineverhogende fantasie. Vereist uitgebreide planning en duidelijke stopwoorden.",
  },
  {
    id: "teacher_student",
    name: "Teacher / student",
    category: "Role Play",
    level: 2,
    description: "Gezaghebbende leerkracht tegenover gehoorzame leerling. Klassiek machtspel. Grenzen rond vernedering en straf van tevoren bespreken.",
  },
  {
    id: "boss_employee",
    name: "Boss / employee",
    category: "Role Play",
    level: 2,
    description: "Baas-medewerker dynamiek met nadruk op hiërarchie en gehoorzaamheid. Kan licht of intens worden. Grenzen en scenario duidelijk afspreken.",
  },
  {
    id: "doctor_patient",
    name: "Doctor / patient",
    category: "Role Play",
    level: 2,
    description: "Medische rollenspellen met een gezaghebbende 'arts' en kwetsbare 'patiënt'. Verkenning van vertrouwen en lichamelijkheid. Grenzen over aanraking zijn essentieel.",
  },
  {
    id: "strangers_scene",
    name: "Strangers scene",
    category: "Role Play",
    level: 2,
    description: "Spelen alsof de partners vreemden zijn die elkaar ontmoeten. Geeft een gevoel van spanning en nieuwheid. Scenario en grenzen altijd van tevoren doornemen.",
  },
  {
    id: "brat_tamer",
    name: "Brat / tamer dynamic",
    category: "Role Play",
    level: 2,
    description: "De submissieve partner (brat) daagt de dominant (tamer) bewust uit. Speels en provocerend. Duidelijke grenzen over straf en vergelding zijn noodzakelijk.",
  },

  // ─── Sensation Play ─────────────────────────────────────────────────────────
  {
    id: "wax_play",
    name: "Wax play",
    category: "Sensation Play",
    level: 2,
    description: "Druppelen van hete kaarsenwas op de huid voor warmtesensaties. Begin altijd laag (veilige hoogte) en gebruik kaarsen zonder additieven. Nooit in de buurt van haar.",
  },
  {
    id: "ice_play",
    name: "Ice play",
    category: "Sensation Play",
    level: 1,
    description: "IJsblokjes over de huid bewegen voor koude, tintelende sensaties. Complementair aan warmtespelen. Altijd bewegen, nooit statisch op gevoelige plekken houden.",
  },
  {
    id: "knife_play",
    name: "Knife play",
    category: "Sensation Play",
    level: 3,
    description: "Gebruik van een mes voor spanning, koude sensaties en psychologische intensiteit. Nooit bedoeld om te snijden. Vereist ervaring en kalmte van beide partners.",
  },
  {
    id: "needle_play",
    name: "Needle play",
    category: "Sensation Play",
    level: 4,
    description: "Naalden door de huid steken voor intense sensaties en esthetische effecten. Vereist medische kennis, steriele materialen en ervaring. Altijd in veilige context.",
  },
  {
    id: "fire_play",
    name: "Fire play",
    category: "Sensation Play",
    level: 4,
    description: "Gebruik van vuur (vlam, alcohol) op of nabij de huid. Visueel indrukwekkend en thermisch intens. Vereist training, brandbestrijder bij de hand en ervaren speler.",
  },
  {
    id: "electro_play",
    name: "Electrostimulation",
    category: "Sensation Play",
    level: 3,
    description: "Elektrische stimulatie via apparaten zoals tens-units. Geeft tintelende tot scherpe sensaties. Nooit boven de taille bij mensen met hartproblemen.",
  },
  {
    id: "wartenberg_wheel",
    name: "Wartenberg wheel",
    category: "Sensation Play",
    level: 2,
    description: "Pinwiel dat over de huid gerold wordt voor tintelende sensaties. Kan licht krabben tot scherp prikken. Schoon instrument, nooit bij open wonden.",
  },
  {
    id: "pinching",
    name: "Pinching / nipple clamps",
    category: "Sensation Play",
    level: 2,
    description: "Knijpen van huid of tepels voor scherpe, gelokaliseerde pijn. Eenvoudig maar intens. Communiceer over voorkeurzones en intensiteit.",
  },
  {
    id: "scratching",
    name: "Scratching",
    category: "Sensation Play",
    level: 1,
    description: "Krabben met nagels of krabwerktuig voor tintelende, brandende sensaties. Kan sporen achterlaten. Communiceer over de zichtbaarheid van tekens.",
  },
  {
    id: "biting",
    name: "Biting",
    category: "Sensation Play",
    level: 1,
    description: "Bijten als uitdrukking van verlangen of dominantie. Intensiteit varieert van zacht tot merkend. Vermijd locaties met grote bloedvaten.",
  },
  {
    id: "tickling",
    name: "Tickling",
    category: "Sensation Play",
    level: 1,
    description: "Kietelen als onderdeel van spel, soms in combinatie met bondage. Kan intens en overweldigend zijn. Safeword is essentieel bij verzwakte positie.",
  },
  {
    id: "temperature_play",
    name: "Temperature play (general)",
    category: "Sensation Play",
    level: 1,
    description: "Bewust variëren van temperatuursensaties (warm/koud). Breed begrip dat wax, ijs en andere technieken omvat. Beginnerspunt voor sensorisch spel.",
  },

  // ─── Breath & Body ──────────────────────────────────────────────────────────
  {
    id: "choking",
    name: "Choking / breath restriction",
    category: "Breath & Body",
    level: 3,
    description: "Druk op de keel of nek voor een gevoel van controle en hypoxie-gerelateerde opwinding. Extreem risico op ernstig letsel of overlijden. Alleen voor gevorderden met diepgaande kennis van anatomie.",
  },
  {
    id: "facesitting",
    name: "Facesitting / smothering",
    category: "Breath & Body",
    level: 2,
    description: "Zitten op het gezicht van de partner, waarbij ademhaling gecontroleerd wordt. Vereist communicatie over ademruimte. Altijd een non-verbaal stopsignaal afspreken.",
  },
  {
    id: "hair_pulling",
    name: "Hair pulling",
    category: "Breath & Body",
    level: 1,
    description: "Trekken aan het haar als daad van dominantie of verlangen. Grijp bij de wortel voor meer controle. Vermijd schokken of rukken.",
  },
  {
    id: "marking",
    name: "Marking / bruising",
    category: "Breath & Body",
    level: 2,
    description: "Kneuzing of bijtreken op het lichaam achterlaten als teken van eigenaarschap. Bespreek of en waar tekens zichtbaar mogen zijn buiten de speelruimte.",
  },
  {
    id: "scarification",
    name: "Scarification / branding",
    category: "Breath & Body",
    level: 4,
    description: "Permanente littekens aanbrengen als lichaamsmodi. Onomkeerbaar en vereist medische kennis. Uitsluitend voor gevorderden met professionele begeleiding.",
  },
  {
    id: "piercing_temp",
    name: "Temporary piercing play",
    category: "Breath & Body",
    level: 4,
    description: "Tijdelijke piercings als sensorisch of esthetisch spel. Steriele naalden, medische kennis en aftercare zijn essentieel. Altijd professioneel materiaal gebruiken.",
  },

  // ─── Exhibition & Voyeurism ─────────────────────────────────────────────────
  {
    id: "exhibitionism",
    name: "Exhibitionism",
    category: "Exhibition & Voyeurism",
    level: 1,
    description: "Opwinding door het tonen van het eigen lichaam aan anderen. Kan variëren van lingerie tot publieke naaktheid. Zorg altijd dat toeschouwers toestemming hebben gegeven.",
  },
  {
    id: "voyeurism",
    name: "Voyeurism",
    category: "Exhibition & Voyeurism",
    level: 1,
    description: "Opwinding door het (consensueel) observeren van anderen. Nooit zonder volledige toestemming van de geobserveerde persoon.",
  },
  {
    id: "public_play",
    name: "Public play (discreet)",
    category: "Exhibition & Voyeurism",
    level: 3,
    description: "Discreet spelen in publieke ruimtes (bijv. knijpen, safeword-fluisteren). Uitdagend en riskant. Altijd discreet en zonder onbewillige derden te betrekken.",
  },
  {
    id: "dogging",
    name: "Outdoor / dogging",
    category: "Exhibition & Voyeurism",
    level: 3,
    description: "Seks of vertoning in openbare (buitenlucht)plekken, soms voor andere aanwezigen. Juridisch gevoelig en vereist bewustzijn van wetten per land.",
  },
  {
    id: "watching_others",
    name: "Watching others (in person)",
    category: "Exhibition & Voyeurism",
    level: 2,
    description: "Consensueel anderen observeren tijdens seksuele activiteit. Vereist duidelijke afspraken met alle betrokkenen. Privacy van de geobserveerden staat voorop.",
  },
  {
    id: "being_watched",
    name: "Being watched",
    category: "Exhibition & Voyeurism",
    level: 1,
    description: "Opwinding door zelf geobserveerd te worden tijdens seksuele activiteit. Bespreek wie mag kijken en in welke context.",
  },
  {
    id: "recording",
    name: "Recording / photography (private)",
    category: "Exhibition & Voyeurism",
    level: 3,
    description: "Privéopnames of -foto's maken tijdens seksuele activiteit. Uitsluitend met volledige toestemming. Bespreek opslaglocatie, deling en verwijdering.",
  },
  {
    id: "webcam",
    name: "Webcam / streaming (private)",
    category: "Exhibition & Voyeurism",
    level: 3,
    description: "Privéstreaming of webcamseks voor een geselecteerd publiek. Bespreek wie toegang heeft. Nooit opslaan of delen zonder expliciete toestemming.",
  },

  // ─── Fetishes ───────────────────────────────────────────────────────────────
  {
    id: "feet",
    name: "Foot worship / feet",
    category: "Fetishes",
    level: 1,
    description: "Opwinding door voeten: aanraken, kussen, masseren of aanbidden. Een van de meest voorkomende fetisjen. Grenzen rond hygiëne en aanraking van tevoren bespreken.",
  },
  {
    id: "leather",
    name: "Leather",
    category: "Fetishes",
    level: 2,
    description: "Opwinding door leer als materiaal: geur, aanraking, kleding. Leer draagt een sterke symbolische lading in de BDSM-cultuur.",
  },
  {
    id: "latex_rubber",
    name: "Latex / rubber",
    category: "Fetishes",
    level: 2,
    description: "Opwinding door latex of rubber kleding, die het lichaam strak omsluit. Aandacht voor latexallergie en smeermiddel voor het aantrekken.",
  },
  {
    id: "lingerie",
    name: "Lingerie / stockings",
    category: "Fetishes",
    level: 1,
    description: "Opwinding door het dragen of zien van ondergoed of kousen. Breed en toegankelijk fetisj. Communiceer over wat gewenste kledingstukken zijn.",
  },
  {
    id: "uniforms",
    name: "Uniforms / costumes",
    category: "Fetishes",
    level: 2,
    description: "Opwinding door uniformen of kostuums (politie, verpleging, etc.). Verbindt rollenspel met fetisj. Bespreek welke rollen en scenario's gewenst zijn.",
  },
  {
    id: "cross_dressing",
    name: "Cross-dressing / forced feminization",
    category: "Fetishes",
    level: 3,
    description: "Opwinding door kleding van een ander gender te dragen, soms als onderdeel van feminisering. Respecteer persoonlijke grenzen en identiteit.",
  },
  {
    id: "pet_play",
    name: "Pet play (puppy / kitten / pony)",
    category: "Fetishes",
    level: 2,
    description: "Een van de partners gedraagt zich als dier (puppy, kitten, pony). Kan speels, sensueel of diepgaand zijn. Afspraken over communicatie (blaffen vs. spreken) zijn nodig.",
  },
  {
    id: "furry",
    name: "Fursuit / furry play",
    category: "Fetishes",
    level: 4,
    description: "Opwinding door het dragen van een dierenkostuum (fursuit) of furry-identiteit. Niche maar vergelijkbaar met andere rollenspelen. Communiceer over grenzen.",
  },
  {
    id: "cuckolding",
    name: "Cuckolding / hotwifing",
    category: "Fetishes",
    level: 3,
    description: "Opwinding waarbij één partner toekijkt of ervan weet dat de ander seks heeft met een derde. Vereist diepgaand vertrouwen en duidelijke grenzen rond seksualiteit en veiligheid.",
  },
  {
    id: "voyeur_sharing",
    name: "Sharing / group play",
    category: "Fetishes",
    level: 3,
    description: "Delen van een partner met anderen of groepsseks. Uitgebreide communicatie, seksuele gezondheidsafspraken en grenzen zijn essentieel.",
  },
  {
    id: "body_worship",
    name: "Body worship",
    category: "Fetishes",
    level: 1,
    description: "Aanbidding van het lichaam van de partner via aanraking, kussen en verbale devotie. Sensueel en verbindend. Bespreek welke lichaamsdelen welkom zijn.",
  },
  {
    id: "stocking_worship",
    name: "Stocking / lingerie worship",
    category: "Fetishes",
    level: 2,
    description: "Opwinding door kousen of lingerie van de partner, inclusief aanraking of besnuffeling. Vergelijkbaar met voetfetisj maar gericht op kleding.",
  },

  // ─── Fluid & Bodily ─────────────────────────────────────────────────────────
  {
    id: "spitting",
    name: "Spitting",
    category: "Fluid & Bodily",
    level: 2,
    description: "Spugen op de partner als daad van vernedering of dominantie. Vereist expliciete toestemming. Hygiënisch en emotioneel gevoelig.",
  },
  {
    id: "watersports",
    name: "Watersports (golden shower)",
    category: "Fluid & Bodily",
    level: 3,
    description: "Golden shower — urineren op of bij de partner. Vereist duidelijke toestemming en afspraken over locatie en hygiëne.",
  },
  {
    id: "scat",
    name: "Scat play",
    category: "Fluid & Bodily",
    level: 4,
    description: "Spelen met ontlasting. Uiterst niche en vereist diepgaande afspraken, hygiëneprotocollen en gezondheidsbewustzijn.",
  },
  {
    id: "cum_play",
    name: "Cum play / facials",
    category: "Fluid & Bodily",
    level: 1,
    description: "Spelen met sperma, waaronder facials of op het lichaam. Communiceer over seksuele gezondheid, testen en wensen.",
  },
  {
    id: "squirting",
    name: "Squirting",
    category: "Fluid & Bodily",
    level: 2,
    description: "Vloeibare ontlading bij genitale stimulatie. Kan voor sommigen intens zijn. Bespreek of dit gewenst is en bereid de omgeving voor.",
  },
  {
    id: "swallowing",
    name: "Swallowing",
    category: "Fluid & Bodily",
    level: 1,
    description: "Sperma inslikken. Communiceer over seksuele gezondheid en tests. Persoonlijke voorkeur dient altijd gerespecteerd te worden.",
  },
  {
    id: "menstrual_play",
    name: "Menstrual play",
    category: "Fluid & Bodily",
    level: 4,
    description: "Seks of spel tijdens de menstruatie. Normaal en veilig voor de meesten, maar bespreek comfort en hygiëne van tevoren.",
  },

  // ─── Anal & Penetration ─────────────────────────────────────────────────────
  {
    id: "anal_sex",
    name: "Anal sex",
    category: "Anal & Penetration",
    level: 2,
    description: "Anale penetratie met penis of speelgoed. Vereist veel glijmiddel, opwarming en communicatie. Nooit haastig beginnen.",
  },
  {
    id: "anal_fingering",
    name: "Anal fingering",
    category: "Anal & Penetration",
    level: 1,
    description: "Anale penetratie met vingers als verkenning of voorbereiding. Altijd korte nagels en glijmiddel gebruiken.",
  },
  {
    id: "pegging",
    name: "Pegging / strap-on",
    category: "Anal & Penetration",
    level: 2,
    description: "Penetratie van de man (of partner zonder penis) met een strap-on door de partner. Communiceer over maat, snelheid en positie.",
  },
  {
    id: "butt_plug",
    name: "Butt plug (wear)",
    category: "Anal & Penetration",
    level: 1,
    description: "Een anaal hulpmiddel om gedragen te worden, van kort tot langdurig. Altijd een bredere basis dan de plug zelf, zodat het niet verloren kan gaan.",
  },
  {
    id: "anal_beads",
    name: "Anal beads",
    category: "Anal & Penetration",
    level: 2,
    description: "Een reeks kralen die anaal ingebracht en uitgetrokken worden voor sensatie. Begin klein, gebruik glijmiddel en communiceer over tempo.",
  },
  {
    id: "fisting_anal",
    name: "Anal fisting",
    category: "Anal & Penetration",
    level: 3,
    description: "Anale penetratie met de volledige hand. Vereist uitgebreide voorbereiding, glijmiddel en vertrouwen. Alleen voor gevorderden.",
  },
  {
    id: "fisting_vaginal",
    name: "Vaginal fisting",
    category: "Anal & Penetration",
    level: 3,
    description: "Vaginale penetratie met de volledige hand. Uitgebreide opwarming, glijmiddel en communicatie zijn noodzakelijk.",
  },
  {
    id: "deep_throat",
    name: "Deep throat",
    category: "Anal & Penetration",
    level: 2,
    description: "Diep oraal seksueel contact waarbij de partner de keel penetreert. Communiceer over ademhaling en non-verbale stopsignalen.",
  },
  {
    id: "rough_sex",
    name: "Rough sex",
    category: "Anal & Penetration",
    level: 2,
    description: "Intens, ruw seksueel contact dat agressiviteit, kracht en dominantie omvat. Bespreek intensiteit, grenzen en aftercare van tevoren uitvoerig.",
  },

  // ─── Aftercare ──────────────────────────────────────────────────────────────
  {
    id: "aftercare_physical",
    name: "Physical aftercare (cuddling, blankets)",
    category: "Aftercare",
    level: 1,
    description: "Fysieke nazorg na spelen: knuffelen, een deken, masseren. Helpt het lichaam en de geest terug te keren naar een veilige basistoestand.",
  },
  {
    id: "aftercare_verbal",
    name: "Verbal reassurance / check-ins",
    category: "Aftercare",
    level: 1,
    description: "Verbale geruststelling na een scène: bevestiging, complimenten, check-ins. Helpt emotionele verwerking na intensief spel.",
  },
  {
    id: "aftercare_alone",
    name: "Alone time after scenes",
    category: "Aftercare",
    level: 2,
    description: "Behoefte aan alleen-tijd na een scène om te verwerken. Soms meer herstellend dan gezelschap. Respecteer deze voorkeur.",
  },
  {
    id: "aftercare_food",
    name: "Food / drink after scenes",
    category: "Aftercare",
    level: 1,
    description: "Eten of drinken na een scène voor herstel van energie en bloedsuiker. Zoet en licht is vaak het beste. Zorg dat dit klaarstaat.",
  },
  {
    id: "aftercare_journaling",
    name: "Journaling / reflection after scenes",
    category: "Aftercare",
    level: 2,
    description: "Schrijven of reflecteren na een scène als verwerkingstool. Kan helpen bij het begrijpen van emoties en het verbeteren van toekomstige scènes.",
  },
];

export const CATEGORIES = Array.from(new Set(KINKS.map((k) => k.category)));

export function getKinksByCategory(category: string): Kink[] {
  return KINKS.filter((k) => k.category === category);
}

export function getKinksByCategoryAndLevel(category: string, maxLevel: number): Kink[] {
  return KINKS.filter((k) => k.category === category && k.level <= maxLevel);
}

export const LEVEL_MAX: Record<string, number> = {
  beginner:  1,
  gevorderd: 2,
  ervaren:   3,
  diepgaand: 4,
};
