/**
 * Immutable wire order used by the retired positional v2 QR payload.
 *
 * Do not derive this from the active catalog and never reorder it. New shares
 * use ID-based v3 payloads; this snapshot exists only so an old v2 character at
 * index N keeps resolving to the same historical kink ID.
 */
export const LEGACY_COMPACT_KINK_IDS_V2 = [
  "spanking_hand", "spanking_implement", "flogging", "caning", "cropping", "paddling",
  "whipping", "belt", "slapping_face", "punching", "trampling", "rope_bondage",
  "shibari", "handcuffs", "leather_cuffs", "spreader_bar", "hogtie", "mummification",
  "straitjacket", "chastity", "gag_ball", "gag_bit", "gag_tape", "blindfold",
  "hood", "collar_leash", "dominance_submission", "master_slave", "owner_pet", "collaring",
  "rules_protocols", "punishment", "humiliation_verbal", "degradation", "praise_kink", "objectification",
  "forced_orgasm", "orgasm_denial", "orgasm_control", "service", "financial_domination", "cnc",
  "interrogation", "capture_scene", "teacher_student", "boss_employee", "doctor_patient", "strangers_scene",
  "brat_tamer", "wax_play", "ice_play", "knife_play", "needle_play", "fire_play",
  "wartenberg_wheel", "pinching", "scratching", "biting", "tickling", "choking",
  "facesitting", "hair_pulling", "marking", "scarification", "exhibitionism", "voyeurism",
  "public_play", "dogging", "watching_others", "being_watched", "recording", "webcam",
  "feet", "leather", "latex_rubber", "lingerie", "uniforms", "furry",
  "cuckolding", "voyeur_sharing", "body_worship", "stocking_worship", "spitting", "scat",
  "cum_play", "squirting", "swallowing", "menstrual_play", "anal_sex", "anal_fingering",
  "pegging", "butt_plug", "anal_beads", "fisting_anal", "fisting_vaginal", "deep_throat",
  "rough_sex", "aftercare_physical", "aftercare_verbal", "aftercare_alone", "aftercare_food", "aftercare_journaling",
  "hoge_hakken_dragen", "korset_dragen", "penisring_cockring", "erotisch_dansen_prive", "kleding_commando", "leren_kleding_dragen",
  "rubber_latex_kleding", "uitdagende_kleding_prive", "verplicht_nudisme_prive", "korset_middelafname", "uitdagende_kleding_publiek", "verplicht_nudisme_publiek",
  "erotisch_dansen_publiek", "crossdressing_mtf", "crossdressing_ftm", "little_speelgoed", "ddlg_mdlb_dynamiek", "little_space",
  "baby_infantiliteit", "fopspeen_fles", "luiers_dragen", "luiers_gebruik", "petplay_collar_id", "petplay_puppy",
  "petplay_kitten", "petplay_pony", "petplay_harnas", "petplay_oortjes", "petplay_leiband", "petplay_geluiden",
  "petplay_kom", "fox_tail_plug", "petplay_kooi", "petplay_kattenbak", "gag_opblaasbaar", "gag_penisvorm",
  "gag_rubber", "borsten_afbinden", "gasmasker", "suspension_rechtop", "suspension_ondersteboven", "suspension_horizontaal",
  "opsluiting_kooi", "opsluiting_donker", "opsluiting_kleine_ruimte", "knielen_ritueel", "in_de_hoek_staan", "rituelen_protocols",
  "straf_standjes", "spreekverbod", "oogcontact_beperkingen", "dienen_als_meubel", "badkamer_controle", "dienen_asbak",
  "lifestyle_247", "tepelklemmen_zacht", "tepelklemmen_hard", "tepelgewichten", "geslacht_klemmen", "geslacht_gewichten",
  "fire_cupping", "celpopping", "naaldjes_borst_buik", "naaldjes_intiem", "artistiek_snijden", "violet_wand_basis",
  "violet_wand_tepels", "violet_wand_intiem", "powerbox_basis", "powerbox_intiem", "shockcollar_prive", "shockcollar_publiek",
  "over_de_knie", "rubber_zweep_slapper", "fire_flogger", "bullwhip", "geur_scent_fetish", "hoge_hakken_aanbidding",
  "vagina_aanbidding", "footjob", "voetgeur", "trampling_voeten", "voeten_in_gezicht", "voeten_in_mond",
  "voet_vernedering", "voetslaaf", "laarzen_aanbidding", "panty_sniffing", "kniekousen_fetish", "watersports_geven",
  "watersports_ontvangen", "urine_intiem", "plas_merken", "plas_desperation", "buiten_plassen", "plas_in_kleding",
  "plas_slaaf", "bloed_play", "katheters_urethral", "klysma_reiniging", "klysma_straf", "rimmen",
  "dubbele_penetratie", "anale_training", "deepthroat", "sounding", "dirty_talk", "titels_aanspreekvormen",
  "joi", "overstimulatie", "geruineerd_orgasme", "keyholding", "free_use", "erotische_hypnose",
  "breeding_creampie", "snowballen", "lactatie", "sleepsack", "predicament_bondage", "vacuumbed",
  "masseur_client", "sekswerker_client", "fantasy_monster", "primal_play", "somnofilie", "body_writing",
  "maskers", "sissificatie", "spiegelspel", "remote_toy_publiek", "filmen_prive", "trio_groepsseks",
  "glory_hole", "cock_worship", "ass_worship", "voedselspel", "fear_play", "figging",
  "ballbusting", "body_slapping", "strafregels_schrijven", "verplichte_reflectie", "privileges_intrekken", "strafklusjes",
  "speeltijd_ontzegd", "avondklok_straf", "opgelegde_stilte", "strafoefeningen", "orgasme_uitstel_straf", "strafspanking",
  "strafessay", "mondzeep", "ochtend_avondritueel", "begroetingsritueel", "verantwoordingsdagboek", "positietraining",
  "wachttraining", "diensttraining", "inspectie_ritueel", "eetritueel", "toestemmingsprotocol", "spraakprotocol",
  "hoog_protocol", "orgasme_op_commando",
] as const;
